// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import golang "github.com/metrix-io/proto/golang"
import mock "github.com/stretchr/testify/mock"

// AuthServiceServer is an autogenerated mock type for the AuthServiceServer type
type AuthServiceServer struct {
	mock.Mock
}

// CreatePermissionInheritance provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) CreatePermissionInheritance(_a0 context.Context, _a1 *golang.CreatePermissionInheritanceRequest) (*golang.CreatePermissionInheritanceResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.CreatePermissionInheritanceResponse
	if rf, ok := ret.Get(0).(func(context.Context, *golang.CreatePermissionInheritanceRequest) *golang.CreatePermissionInheritanceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.CreatePermissionInheritanceResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.CreatePermissionInheritanceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePermissions provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) CreatePermissions(_a0 context.Context, _a1 *golang.CreatePermissionsRequest) (*golang.PermissionAssignments, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.PermissionAssignments
	if rf, ok := ret.Get(0).(func(context.Context, *golang.CreatePermissionsRequest) *golang.PermissionAssignments); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.PermissionAssignments)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.CreatePermissionsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePermissionInheritance provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) DeletePermissionInheritance(_a0 context.Context, _a1 *golang.DeletePermissionInheritanceRequest) (*golang.DeletePermissionInheritanceResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.DeletePermissionInheritanceResponse
	if rf, ok := ret.Get(0).(func(context.Context, *golang.DeletePermissionInheritanceRequest) *golang.DeletePermissionInheritanceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.DeletePermissionInheritanceResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.DeletePermissionInheritanceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePermissions provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) DeletePermissions(_a0 context.Context, _a1 *golang.DeletePermissionsRequest) (*golang.DeletePermissionsRequest, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.DeletePermissionsRequest
	if rf, ok := ret.Get(0).(func(context.Context, *golang.DeletePermissionsRequest) *golang.DeletePermissionsRequest); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.DeletePermissionsRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.DeletePermissionsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSubject provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) DeleteSubject(_a0 context.Context, _a1 *golang.DeleteSubjectRequest) (*golang.DeleteSubjectResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.DeleteSubjectResponse
	if rf, ok := ret.Get(0).(func(context.Context, *golang.DeleteSubjectRequest) *golang.DeleteSubjectResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.DeleteSubjectResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.DeleteSubjectRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissions provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) GetPermissions(_a0 context.Context, _a1 *golang.GetPermissionsRequest) (*golang.PermissionAssignments, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.PermissionAssignments
	if rf, ok := ret.Get(0).(func(context.Context, *golang.GetPermissionsRequest) *golang.PermissionAssignments); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.PermissionAssignments)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.GetPermissionsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasPermissions provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) HasPermissions(_a0 context.Context, _a1 *golang.HasPermissionsRequest) (*golang.HasPermissionsResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.HasPermissionsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *golang.HasPermissionsRequest) *golang.HasPermissionsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.HasPermissionsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.HasPermissionsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) Login(_a0 context.Context, _a1 *golang.LoginRequest) (*golang.AccessToken, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.AccessToken
	if rf, ok := ret.Get(0).(func(context.Context, *golang.LoginRequest) *golang.AccessToken); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.AccessToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.LoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) Logout(_a0 context.Context, _a1 *golang.LogoutRequest) (*golang.LogoutResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.LogoutResponse
	if rf, ok := ret.Get(0).(func(context.Context, *golang.LogoutRequest) *golang.LogoutResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.LogoutResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.LogoutRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogoutAll provides a mock function with given fields: _a0, _a1
func (_m *AuthServiceServer) LogoutAll(_a0 context.Context, _a1 *golang.LogoutAllRequest) (*golang.LogoutAllResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *golang.LogoutAllResponse
	if rf, ok := ret.Get(0).(func(context.Context, *golang.LogoutAllRequest) *golang.LogoutAllResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golang.LogoutAllResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *golang.LogoutAllRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
