// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account-service.proto

package golang // import "github.com/metrix-io/proto/golang"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Account represents a user account.
//
// An account only contain the user's primary email address and
// phone number (if available). To view a secondary phone numbers
// or email addresses use one of the other RPC methods.
type Account struct {
	// The identifier of the user.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Subject is the fully qualified security identifier for this account.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Username. The maximum length is 15 characters.
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// User's preferred e-mail address.
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// True if the user's e-mail address has been verified; otherwise false.
	EmailVerified bool     `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Profile       *Profile `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	// User's preferred phone number.
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// True if the user's phone number has been verified; otherwise false.
	PhoneNumberVerified bool `protobuf:"varint,8,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	// Unix timestamp when user account was created.
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp when user information was last updated.
	UpdatedAt int64 `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Unix timestamp when account was cancelled. Cancelled accounts are
	// automatically removed after one month.
	CancelledAt int64 `protobuf:"varint,11,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	// Unix timestamp when account was last logged in.
	LastLoginAt          int64    `protobuf:"varint,12,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *Account) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Account) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Account) GetPhoneNumberVerified() bool {
	if m != nil {
		return m.PhoneNumberVerified
	}
	return false
}

func (m *Account) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Account) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Account) GetCancelledAt() int64 {
	if m != nil {
		return m.CancelledAt
	}
	return 0
}

func (m *Account) GetLastLoginAt() int64 {
	if m != nil {
		return m.LastLoginAt
	}
	return 0
}

// *
// Profile is based loosely on the OpenID Connect userinfo specification:
// https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
//
// Be aware most fields are usually empty.
type Profile struct {
	// End-User's full name. The maximum length is 100 characters.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// First name(s) of the user. The maximum length is 30 characters.
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name(s) of the user. The maximum length is 30 characters.
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Middle name(s) of the user. The maximum length is 30 characters.
	MiddleName string `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	// Casual name of the user that may or may not be the same as the given_name.
	// The maximum length is 15 characters.
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// URL of user profile page. The maximum length is 255 characters.
	Profile string `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	// URL of user picture. The maximum length is 255 characters.
	Picture string `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	// URL of user web page or blog.
	Website string `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	// The gender is either "male", "female", "genderqueer" or empty.
	Gender string `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	// User's birthday is formatted in YYYY-MM-DD format.
	Birthdate string `protobuf:"bytes,10,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	// String from a time zone database representing the user's time zone.
	Zoneinfo string `protobuf:"bytes,11,opt,name=zoneinfo,proto3" json:"zoneinfo,omitempty"`
	// User's locale, represented as a BCP47 [RFC5646] language tag.
	Locale               string   `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{1}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Profile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Profile) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Profile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Profile) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *Profile) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Profile) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *Profile) GetZoneinfo() string {
	if m != nil {
		return m.Zoneinfo
	}
	return ""
}

func (m *Profile) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

// *
// Email contains an email address. Email addresses are always unique.
type Email struct {
	// Unique email identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The account to which this email belongs. An email can only belong
	// to 1 account.
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Email address.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// True if this email address has been verified; otherwise false.
	IsVerified bool `protobuf:"varint,4,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	// True if this is the user's preferred email address. Only 1 email address
	// can be primary.
	IsPrimary bool `protobuf:"varint,5,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	// Unix timestamp when email was created.
	CreatedAt int64 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp when email was last updated.
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{2}
}
func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (dst *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(dst, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Email) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Email) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *Email) GetIsPrimary() bool {
	if m != nil {
		return m.IsPrimary
	}
	return false
}

func (m *Email) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Email) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GetAccountByIDRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountByIDRequest) Reset()         { *m = GetAccountByIDRequest{} }
func (m *GetAccountByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountByIDRequest) ProtoMessage()    {}
func (*GetAccountByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{3}
}
func (m *GetAccountByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountByIDRequest.Unmarshal(m, b)
}
func (m *GetAccountByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountByIDRequest.Merge(dst, src)
}
func (m *GetAccountByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountByIDRequest.Size(m)
}
func (m *GetAccountByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountByIDRequest proto.InternalMessageInfo

func (m *GetAccountByIDRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type CreateAccountRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Profile              *Profile `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{4}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateAccountRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

// *
// UpdateAccountRequest allows to update user profile details.
// TODO
type UpdateAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Profile              *Profile `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{5}
}
func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(dst, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateAccountRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

// *
// UpdateAccount sends an empty response when the account has
// successfully been updated.
//
// Returns InvalidArgument errors if any of the fields are invalid.
type UpdateAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{6}
}
func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(dst, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

type CheckCredentialsRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckCredentialsRequest) Reset()         { *m = CheckCredentialsRequest{} }
func (m *CheckCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*CheckCredentialsRequest) ProtoMessage()    {}
func (*CheckCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{7}
}
func (m *CheckCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckCredentialsRequest.Unmarshal(m, b)
}
func (m *CheckCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckCredentialsRequest.Marshal(b, m, deterministic)
}
func (dst *CheckCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckCredentialsRequest.Merge(dst, src)
}
func (m *CheckCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_CheckCredentialsRequest.Size(m)
}
func (m *CheckCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckCredentialsRequest proto.InternalMessageInfo

func (m *CheckCredentialsRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CheckCredentialsRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{8}
}
func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(dst, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordResponse) Reset()         { *m = ForgotPasswordResponse{} }
func (m *ForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordResponse) ProtoMessage()    {}
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{9}
}
func (m *ForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordResponse.Unmarshal(m, b)
}
func (m *ForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordResponse.Merge(dst, src)
}
func (m *ForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordResponse.Size(m)
}
func (m *ForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordResponse proto.InternalMessageInfo

type CheckResetTokenRequest struct {
	ResetToken           string   `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResetTokenRequest) Reset()         { *m = CheckResetTokenRequest{} }
func (m *CheckResetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CheckResetTokenRequest) ProtoMessage()    {}
func (*CheckResetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{10}
}
func (m *CheckResetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResetTokenRequest.Unmarshal(m, b)
}
func (m *CheckResetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResetTokenRequest.Marshal(b, m, deterministic)
}
func (dst *CheckResetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResetTokenRequest.Merge(dst, src)
}
func (m *CheckResetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CheckResetTokenRequest.Size(m)
}
func (m *CheckResetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResetTokenRequest proto.InternalMessageInfo

func (m *CheckResetTokenRequest) GetResetToken() string {
	if m != nil {
		return m.ResetToken
	}
	return ""
}

type CheckResetTokenResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResetTokenResponse) Reset()         { *m = CheckResetTokenResponse{} }
func (m *CheckResetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResetTokenResponse) ProtoMessage()    {}
func (*CheckResetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{11}
}
func (m *CheckResetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResetTokenResponse.Unmarshal(m, b)
}
func (m *CheckResetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResetTokenResponse.Marshal(b, m, deterministic)
}
func (dst *CheckResetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResetTokenResponse.Merge(dst, src)
}
func (m *CheckResetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResetTokenResponse.Size(m)
}
func (m *CheckResetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResetTokenResponse proto.InternalMessageInfo

func (m *CheckResetTokenResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type ResetPasswordRequest struct {
	ResetToken           string   `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{12}
}
func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(dst, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetResetToken() string {
	if m != nil {
		return m.ResetToken
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{13}
}
func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(dst, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

type UpdatePasswordRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{14}
}
func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(dst, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{15}
}
func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(dst, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

type VerifyEmailRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{16}
}
func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(dst, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailResponse) Reset()         { *m = VerifyEmailResponse{} }
func (m *VerifyEmailResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailResponse) ProtoMessage()    {}
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{17}
}
func (m *VerifyEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailResponse.Unmarshal(m, b)
}
func (m *VerifyEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailResponse.Marshal(b, m, deterministic)
}
func (dst *VerifyEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailResponse.Merge(dst, src)
}
func (m *VerifyEmailResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailResponse.Size(m)
}
func (m *VerifyEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailResponse proto.InternalMessageInfo

type ResendVerificationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendVerificationRequest) Reset()         { *m = ResendVerificationRequest{} }
func (m *ResendVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*ResendVerificationRequest) ProtoMessage()    {}
func (*ResendVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{18}
}
func (m *ResendVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendVerificationRequest.Unmarshal(m, b)
}
func (m *ResendVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendVerificationRequest.Marshal(b, m, deterministic)
}
func (dst *ResendVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendVerificationRequest.Merge(dst, src)
}
func (m *ResendVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_ResendVerificationRequest.Size(m)
}
func (m *ResendVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResendVerificationRequest proto.InternalMessageInfo

func (m *ResendVerificationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResendVerificationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendVerificationResponse) Reset()         { *m = ResendVerificationResponse{} }
func (m *ResendVerificationResponse) String() string { return proto.CompactTextString(m) }
func (*ResendVerificationResponse) ProtoMessage()    {}
func (*ResendVerificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{19}
}
func (m *ResendVerificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendVerificationResponse.Unmarshal(m, b)
}
func (m *ResendVerificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendVerificationResponse.Marshal(b, m, deterministic)
}
func (dst *ResendVerificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendVerificationResponse.Merge(dst, src)
}
func (m *ResendVerificationResponse) XXX_Size() int {
	return xxx_messageInfo_ResendVerificationResponse.Size(m)
}
func (m *ResendVerificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendVerificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResendVerificationResponse proto.InternalMessageInfo

type CancelAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAccountRequest) Reset()         { *m = CancelAccountRequest{} }
func (m *CancelAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CancelAccountRequest) ProtoMessage()    {}
func (*CancelAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{20}
}
func (m *CancelAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAccountRequest.Unmarshal(m, b)
}
func (m *CancelAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CancelAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAccountRequest.Merge(dst, src)
}
func (m *CancelAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CancelAccountRequest.Size(m)
}
func (m *CancelAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAccountRequest proto.InternalMessageInfo

func (m *CancelAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type CancelAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAccountResponse) Reset()         { *m = CancelAccountResponse{} }
func (m *CancelAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CancelAccountResponse) ProtoMessage()    {}
func (*CancelAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{21}
}
func (m *CancelAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAccountResponse.Unmarshal(m, b)
}
func (m *CancelAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAccountResponse.Marshal(b, m, deterministic)
}
func (dst *CancelAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAccountResponse.Merge(dst, src)
}
func (m *CancelAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CancelAccountResponse.Size(m)
}
func (m *CancelAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAccountResponse proto.InternalMessageInfo

type CheckUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsernameRequest) Reset()         { *m = CheckUsernameRequest{} }
func (m *CheckUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUsernameRequest) ProtoMessage()    {}
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{22}
}
func (m *CheckUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsernameRequest.Unmarshal(m, b)
}
func (m *CheckUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsernameRequest.Marshal(b, m, deterministic)
}
func (dst *CheckUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsernameRequest.Merge(dst, src)
}
func (m *CheckUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUsernameRequest.Size(m)
}
func (m *CheckUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsernameRequest proto.InternalMessageInfo

func (m *CheckUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CheckUsernameResponse struct {
	IsAvailable          bool     `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsernameResponse) Reset()         { *m = CheckUsernameResponse{} }
func (m *CheckUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUsernameResponse) ProtoMessage()    {}
func (*CheckUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{23}
}
func (m *CheckUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsernameResponse.Unmarshal(m, b)
}
func (m *CheckUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsernameResponse.Marshal(b, m, deterministic)
}
func (dst *CheckUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsernameResponse.Merge(dst, src)
}
func (m *CheckUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUsernameResponse.Size(m)
}
func (m *CheckUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsernameResponse proto.InternalMessageInfo

func (m *CheckUsernameResponse) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

type CheckEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEmailRequest) Reset()         { *m = CheckEmailRequest{} }
func (m *CheckEmailRequest) String() string { return proto.CompactTextString(m) }
func (*CheckEmailRequest) ProtoMessage()    {}
func (*CheckEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{24}
}
func (m *CheckEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEmailRequest.Unmarshal(m, b)
}
func (m *CheckEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEmailRequest.Marshal(b, m, deterministic)
}
func (dst *CheckEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEmailRequest.Merge(dst, src)
}
func (m *CheckEmailRequest) XXX_Size() int {
	return xxx_messageInfo_CheckEmailRequest.Size(m)
}
func (m *CheckEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEmailRequest proto.InternalMessageInfo

func (m *CheckEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CheckEmailResponse struct {
	IsAvailable          bool     `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEmailResponse) Reset()         { *m = CheckEmailResponse{} }
func (m *CheckEmailResponse) String() string { return proto.CompactTextString(m) }
func (*CheckEmailResponse) ProtoMessage()    {}
func (*CheckEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_0a29f60e2872c801, []int{25}
}
func (m *CheckEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEmailResponse.Unmarshal(m, b)
}
func (m *CheckEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEmailResponse.Marshal(b, m, deterministic)
}
func (dst *CheckEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEmailResponse.Merge(dst, src)
}
func (m *CheckEmailResponse) XXX_Size() int {
	return xxx_messageInfo_CheckEmailResponse.Size(m)
}
func (m *CheckEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEmailResponse proto.InternalMessageInfo

func (m *CheckEmailResponse) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

func init() {
	proto.RegisterType((*Account)(nil), "metrixio.Account")
	proto.RegisterType((*Profile)(nil), "metrixio.Profile")
	proto.RegisterType((*Email)(nil), "metrixio.Email")
	proto.RegisterType((*GetAccountByIDRequest)(nil), "metrixio.GetAccountByIDRequest")
	proto.RegisterType((*CreateAccountRequest)(nil), "metrixio.CreateAccountRequest")
	proto.RegisterType((*UpdateAccountRequest)(nil), "metrixio.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "metrixio.UpdateAccountResponse")
	proto.RegisterType((*CheckCredentialsRequest)(nil), "metrixio.CheckCredentialsRequest")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "metrixio.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordResponse)(nil), "metrixio.ForgotPasswordResponse")
	proto.RegisterType((*CheckResetTokenRequest)(nil), "metrixio.CheckResetTokenRequest")
	proto.RegisterType((*CheckResetTokenResponse)(nil), "metrixio.CheckResetTokenResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "metrixio.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "metrixio.ResetPasswordResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "metrixio.UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "metrixio.UpdatePasswordResponse")
	proto.RegisterType((*VerifyEmailRequest)(nil), "metrixio.VerifyEmailRequest")
	proto.RegisterType((*VerifyEmailResponse)(nil), "metrixio.VerifyEmailResponse")
	proto.RegisterType((*ResendVerificationRequest)(nil), "metrixio.ResendVerificationRequest")
	proto.RegisterType((*ResendVerificationResponse)(nil), "metrixio.ResendVerificationResponse")
	proto.RegisterType((*CancelAccountRequest)(nil), "metrixio.CancelAccountRequest")
	proto.RegisterType((*CancelAccountResponse)(nil), "metrixio.CancelAccountResponse")
	proto.RegisterType((*CheckUsernameRequest)(nil), "metrixio.CheckUsernameRequest")
	proto.RegisterType((*CheckUsernameResponse)(nil), "metrixio.CheckUsernameResponse")
	proto.RegisterType((*CheckEmailRequest)(nil), "metrixio.CheckEmailRequest")
	proto.RegisterType((*CheckEmailResponse)(nil), "metrixio.CheckEmailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	// *
	// CreateAccountRequest creates a new account.
	//
	// Errors:
	// - FAILED_PRECONDITION if the email or username is already in use.
	// - INVALID_ARGUMENT if any of the fields are invalid.
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*Account, error)
	// *
	// CheckUsername returns true when a specified username is still
	// available, otherwise false.
	CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameResponse, error)
	// *
	// CheckEmail returns true when a specified email address is still
	// available, otherwise false.
	CheckEmail(ctx context.Context, in *CheckEmailRequest, opts ...grpc.CallOption) (*CheckEmailResponse, error)
	// *
	// CheckCredentialsRequest verifies if a username/email + password
	// combination is valid. The login-field may contain either a username
	// or email address.
	//
	// Returns the user's account on success.
	//
	// Errors:
	// - UNAUTHENTICATED if credentials are invalid.
	CheckCredentials(ctx context.Context, in *CheckCredentialsRequest, opts ...grpc.CallOption) (*Account, error)
	// *
	// CheckResetToken checks whether a reset token is valid. A reset token is invalid
	// if it does not exist, has expired or has already been used.
	CheckResetToken(ctx context.Context, in *CheckResetTokenRequest, opts ...grpc.CallOption) (*CheckResetTokenResponse, error)
	// *
	// Returns an account and profile by it's ID.
	//
	// Errors:
	// - PERMISSION_DENIED if logged in subject has insufficient privileges.
	// - NOT_FOUND if account could not be found.
	GetAccountByID(ctx context.Context, in *GetAccountByIDRequest, opts ...grpc.CallOption) (*Account, error)
	// *
	// ResendVerificationRequest schedules a reset password email. The reset
	// link expires after 3 hours.
	//
	// Returns an empty response when a new forgot password email has successfully
	// been scheduled. Normally an email arrives within a couple of minutes.
	//
	// Errors:
	// - NOT_FOUND if the email address did not match any account.
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
	// *
	// ResetPassword updates an account password using a reset token
	// as proof.
	//
	// Returns an empty response when the password was updated successfully.
	//
	// Errors:
	// - NOT_FOUND if the reset token does not exist, has already been used
	//   or has expired.
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	// *
	// UpdatePasswordRequest changes an account password with a user password as
	// verification.
	//
	// UpdatePas`sword sends an empty response when the password was updated
	// successfully.
	//
	// Errors:
	// - UNAUTHENTICATED if the verification password was invalid.
	// - NOT_FOUND error if the account could not be found.
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error)
	// *
	// VerifyEmailRequest verifies an email address.
	//
	// Returns an empty response when the email was successfully verified.
	//
	// Errors:
	// - NOT_FOUND if token is invalid.
	// - FAILED_PRECONDITION if the email was already verified.
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
	// *
	// ResendVerificationRequest requests a new verification email to
	// a newly registered account that has not been verified yet.
	//
	// Returns an empty response when a new verification email was scheduled.
	// Normally an email arrives within a couple of minutes.
	//
	// Errors:
	// - NOT_FOUND if the email address did not match any account.
	// - FAILED_PRECONDITION if the specified email address has already
	//   been verified.
	ResendVerification(ctx context.Context, in *ResendVerificationRequest, opts ...grpc.CallOption) (*ResendVerificationResponse, error)
	// *
	// CancelAccount disables an account and removes all auth tokens
	// associated with the account.
	//
	// Cancelled accounts are completely removed after 14 days.
	//
	// To regain access to a cancelled account before the account is
	// permanently deleted send an email to support@metrix.io
	//
	// Returns an empty response when cancellation was successful.
	//
	// Errors:
	// - NOT_FOUND if the account could not be found.
	// - PERMISSION_DENIED if logged in subject has insufficient privileges.
	CancelAccount(ctx context.Context, in *CancelAccountRequest, opts ...grpc.CallOption) (*CancelAccountResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameResponse, error) {
	out := new(CheckUsernameResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/CheckUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CheckEmail(ctx context.Context, in *CheckEmailRequest, opts ...grpc.CallOption) (*CheckEmailResponse, error) {
	out := new(CheckEmailResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/CheckEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CheckCredentials(ctx context.Context, in *CheckCredentialsRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/CheckCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CheckResetToken(ctx context.Context, in *CheckResetTokenRequest, opts ...grpc.CallOption) (*CheckResetTokenResponse, error) {
	out := new(CheckResetTokenResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/CheckResetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountByID(ctx context.Context, in *GetAccountByIDRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/GetAccountByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error) {
	out := new(UpdatePasswordResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/VerifyEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ResendVerification(ctx context.Context, in *ResendVerificationRequest, opts ...grpc.CallOption) (*ResendVerificationResponse, error) {
	out := new(ResendVerificationResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/ResendVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CancelAccount(ctx context.Context, in *CancelAccountRequest, opts ...grpc.CallOption) (*CancelAccountResponse, error) {
	out := new(CancelAccountResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AccountService/CancelAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	// *
	// CreateAccountRequest creates a new account.
	//
	// Errors:
	// - FAILED_PRECONDITION if the email or username is already in use.
	// - INVALID_ARGUMENT if any of the fields are invalid.
	CreateAccount(context.Context, *CreateAccountRequest) (*Account, error)
	// *
	// CheckUsername returns true when a specified username is still
	// available, otherwise false.
	CheckUsername(context.Context, *CheckUsernameRequest) (*CheckUsernameResponse, error)
	// *
	// CheckEmail returns true when a specified email address is still
	// available, otherwise false.
	CheckEmail(context.Context, *CheckEmailRequest) (*CheckEmailResponse, error)
	// *
	// CheckCredentialsRequest verifies if a username/email + password
	// combination is valid. The login-field may contain either a username
	// or email address.
	//
	// Returns the user's account on success.
	//
	// Errors:
	// - UNAUTHENTICATED if credentials are invalid.
	CheckCredentials(context.Context, *CheckCredentialsRequest) (*Account, error)
	// *
	// CheckResetToken checks whether a reset token is valid. A reset token is invalid
	// if it does not exist, has expired or has already been used.
	CheckResetToken(context.Context, *CheckResetTokenRequest) (*CheckResetTokenResponse, error)
	// *
	// Returns an account and profile by it's ID.
	//
	// Errors:
	// - PERMISSION_DENIED if logged in subject has insufficient privileges.
	// - NOT_FOUND if account could not be found.
	GetAccountByID(context.Context, *GetAccountByIDRequest) (*Account, error)
	// *
	// ResendVerificationRequest schedules a reset password email. The reset
	// link expires after 3 hours.
	//
	// Returns an empty response when a new forgot password email has successfully
	// been scheduled. Normally an email arrives within a couple of minutes.
	//
	// Errors:
	// - NOT_FOUND if the email address did not match any account.
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
	// *
	// ResetPassword updates an account password using a reset token
	// as proof.
	//
	// Returns an empty response when the password was updated successfully.
	//
	// Errors:
	// - NOT_FOUND if the reset token does not exist, has already been used
	//   or has expired.
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	// *
	// UpdatePasswordRequest changes an account password with a user password as
	// verification.
	//
	// UpdatePas`sword sends an empty response when the password was updated
	// successfully.
	//
	// Errors:
	// - UNAUTHENTICATED if the verification password was invalid.
	// - NOT_FOUND error if the account could not be found.
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error)
	// *
	// VerifyEmailRequest verifies an email address.
	//
	// Returns an empty response when the email was successfully verified.
	//
	// Errors:
	// - NOT_FOUND if token is invalid.
	// - FAILED_PRECONDITION if the email was already verified.
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	// *
	// ResendVerificationRequest requests a new verification email to
	// a newly registered account that has not been verified yet.
	//
	// Returns an empty response when a new verification email was scheduled.
	// Normally an email arrives within a couple of minutes.
	//
	// Errors:
	// - NOT_FOUND if the email address did not match any account.
	// - FAILED_PRECONDITION if the specified email address has already
	//   been verified.
	ResendVerification(context.Context, *ResendVerificationRequest) (*ResendVerificationResponse, error)
	// *
	// CancelAccount disables an account and removes all auth tokens
	// associated with the account.
	//
	// Cancelled accounts are completely removed after 14 days.
	//
	// To regain access to a cancelled account before the account is
	// permanently deleted send an email to support@metrix.io
	//
	// Returns an empty response when cancellation was successful.
	//
	// Errors:
	// - NOT_FOUND if the account could not be found.
	// - PERMISSION_DENIED if logged in subject has insufficient privileges.
	CancelAccount(context.Context, *CancelAccountRequest) (*CancelAccountResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CheckUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CheckUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/CheckUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CheckUsername(ctx, req.(*CheckUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CheckEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CheckEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/CheckEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CheckEmail(ctx, req.(*CheckEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CheckCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CheckCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/CheckCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CheckCredentials(ctx, req.(*CheckCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CheckResetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckResetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CheckResetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/CheckResetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CheckResetToken(ctx, req.(*CheckResetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/GetAccountByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountByID(ctx, req.(*GetAccountByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/VerifyEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ResendVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ResendVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/ResendVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ResendVerification(ctx, req.(*ResendVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CancelAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CancelAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AccountService/CancelAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CancelAccount(ctx, req.(*CancelAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metrixio.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
		{
			MethodName: "CheckUsername",
			Handler:    _AccountService_CheckUsername_Handler,
		},
		{
			MethodName: "CheckEmail",
			Handler:    _AccountService_CheckEmail_Handler,
		},
		{
			MethodName: "CheckCredentials",
			Handler:    _AccountService_CheckCredentials_Handler,
		},
		{
			MethodName: "CheckResetToken",
			Handler:    _AccountService_CheckResetToken_Handler,
		},
		{
			MethodName: "GetAccountByID",
			Handler:    _AccountService_GetAccountByID_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _AccountService_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AccountService_ResetPassword_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _AccountService_UpdatePassword_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _AccountService_VerifyEmail_Handler,
		},
		{
			MethodName: "ResendVerification",
			Handler:    _AccountService_ResendVerification_Handler,
		},
		{
			MethodName: "CancelAccount",
			Handler:    _AccountService_CancelAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/account-service.proto",
}

func init() {
	proto.RegisterFile("proto/account-service.proto", fileDescriptor_account_service_0a29f60e2872c801)
}

var fileDescriptor_account_service_0a29f60e2872c801 = []byte{
	// 1105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0xec, 0x24, 0xb6, 0x8e, 0x62, 0x43, 0xb7, 0x76, 0xaa, 0x2a, 0x09, 0xb1, 0x55, 0x98,
	0x09, 0x30, 0x49, 0x86, 0xf0, 0x37, 0x70, 0xe7, 0xa6, 0x94, 0x09, 0x74, 0x3a, 0x19, 0x41, 0x3a,
	0x4c, 0x6f, 0x34, 0xb2, 0xb4, 0x71, 0x96, 0xc8, 0x92, 0xd1, 0xae, 0x13, 0xc2, 0x5b, 0x70, 0xc1,
	0x4b, 0x71, 0xc1, 0x83, 0xf0, 0x14, 0xcc, 0xae, 0x56, 0xf2, 0x6a, 0xad, 0x38, 0xf4, 0xce, 0xe7,
	0x67, 0xcf, 0xcf, 0x77, 0xce, 0xf9, 0x94, 0xc0, 0xce, 0x2c, 0x4b, 0x59, 0x7a, 0x1c, 0x84, 0x61,
	0x3a, 0x4f, 0xd8, 0x21, 0xc5, 0xd9, 0x0d, 0x09, 0xf1, 0x91, 0xd0, 0xa2, 0xf6, 0x14, 0xb3, 0x8c,
	0xfc, 0x4e, 0x52, 0xf7, 0xaf, 0x26, 0xb4, 0x46, 0xb9, 0x0f, 0xea, 0x42, 0x83, 0x44, 0xb6, 0x31,
	0x30, 0x0e, 0x4c, 0xaf, 0x41, 0x22, 0x64, 0x43, 0x8b, 0xce, 0xc7, 0xbf, 0xe2, 0x90, 0xd9, 0x0d,
	0xa1, 0x2c, 0x44, 0xe4, 0x40, 0x7b, 0x4e, 0x71, 0x96, 0x04, 0x53, 0x6c, 0x37, 0x85, 0xa9, 0x94,
	0x51, 0x0f, 0x36, 0xf0, 0x34, 0x20, 0xb1, 0xbd, 0x2e, 0x0c, 0xb9, 0x80, 0x3e, 0x82, 0xae, 0xf8,
	0xe1, 0xdf, 0xe0, 0x8c, 0x5c, 0x12, 0x1c, 0xd9, 0x1b, 0x03, 0xe3, 0xa0, 0xed, 0x75, 0x84, 0xf6,
	0x8d, 0x54, 0xa2, 0x4f, 0xa1, 0x35, 0xcb, 0xd2, 0x4b, 0x12, 0x63, 0x7b, 0x73, 0x60, 0x1c, 0x58,
	0x27, 0x8f, 0x8e, 0x8a, 0x52, 0x8f, 0xce, 0x73, 0x83, 0x57, 0x78, 0xa0, 0x21, 0x6c, 0xcd, 0xae,
	0xd2, 0x04, 0xfb, 0xc9, 0x7c, 0x3a, 0xc6, 0x99, 0xdd, 0x12, 0x09, 0x2d, 0xa1, 0x7b, 0x2d, 0x54,
	0xe8, 0x04, 0xfa, 0xaa, 0xcb, 0x22, 0x7b, 0x5b, 0x64, 0x7f, 0xac, 0xf8, 0x96, 0x35, 0xec, 0x01,
	0x84, 0x19, 0x0e, 0x18, 0x8e, 0xfc, 0x80, 0xd9, 0xe6, 0xc0, 0x38, 0x68, 0x7a, 0xa6, 0xd4, 0x8c,
	0x18, 0x37, 0xcf, 0x67, 0x51, 0x61, 0x86, 0xdc, 0x2c, 0x35, 0x23, 0xc6, 0x8b, 0x0a, 0x83, 0x24,
	0xc4, 0x71, 0x9c, 0x3b, 0x58, 0xc2, 0xc1, 0x2a, 0x75, 0x23, 0x86, 0x5c, 0xe8, 0xc4, 0x01, 0x65,
	0x7e, 0x9c, 0x4e, 0x48, 0xc2, 0x7d, 0xb6, 0x72, 0x1f, 0xae, 0x7c, 0xc5, 0x75, 0x23, 0xe6, 0xfe,
	0xd3, 0x80, 0x96, 0x6c, 0x18, 0x21, 0x58, 0x17, 0x48, 0xe7, 0x93, 0x11, 0xbf, 0x79, 0x15, 0x97,
	0x24, 0xa3, 0xcc, 0x17, 0x96, 0x7c, 0x3c, 0xa6, 0xd0, 0xbc, 0xe6, 0xe6, 0x1d, 0x30, 0x45, 0x0a,
	0x75, 0x42, 0x5c, 0x21, 0x8c, 0xfb, 0x60, 0x4d, 0x49, 0x14, 0xc5, 0x38, 0x37, 0xe7, 0x73, 0x82,
	0x5c, 0x25, 0x1c, 0x1c, 0x68, 0x27, 0x24, 0xbc, 0x16, 0xd6, 0x8d, 0xfc, 0x71, 0x21, 0xf3, 0xa5,
	0x50, 0x27, 0x64, 0x2e, 0xc6, 0xc1, 0x2d, 0x24, 0x64, 0xf3, 0x0c, 0xcb, 0x49, 0x14, 0x22, 0xb7,
	0xdc, 0xe2, 0x31, 0x25, 0x0c, 0x0b, 0xdc, 0x4d, 0xaf, 0x10, 0xd1, 0x36, 0x6c, 0x4e, 0x70, 0x12,
	0xe1, 0x4c, 0xe0, 0x6c, 0x7a, 0x52, 0x42, 0xbb, 0x60, 0x8e, 0x49, 0xc6, 0xae, 0x38, 0xaa, 0x02,
	0x63, 0xd3, 0x5b, 0x28, 0x78, 0x7d, 0x7f, 0xa4, 0x09, 0x26, 0xc9, 0x65, 0x2a, 0xf0, 0x35, 0xbd,
	0x52, 0xe6, 0x11, 0xe3, 0x34, 0x0c, 0x62, 0x2c, 0x50, 0x35, 0x3d, 0x29, 0xb9, 0x7f, 0x1b, 0xb0,
	0xf1, 0x9d, 0x58, 0x45, 0x7d, 0xcd, 0xf7, 0x00, 0xe4, 0x95, 0xf8, 0x24, 0x2a, 0xa0, 0x94, 0x9a,
	0xb3, 0x68, 0xb1, 0xcf, 0x4d, 0x75, 0x9f, 0xf7, 0xc1, 0x22, 0x74, 0xb1, 0x4e, 0xeb, 0x62, 0x9d,
	0x80, 0x50, 0x75, 0x8b, 0x08, 0xf5, 0x67, 0x19, 0x99, 0x06, 0xd9, 0x9d, 0x5c, 0x76, 0x93, 0xd0,
	0xf3, 0x5c, 0xa1, 0x2d, 0xd9, 0xe6, 0xea, 0x25, 0x6b, 0x69, 0x4b, 0xe6, 0x7e, 0x05, 0xfd, 0xef,
	0x31, 0x93, 0x77, 0xfb, 0xfc, 0xee, 0xec, 0x85, 0x87, 0x7f, 0x9b, 0x63, 0xca, 0xb4, 0x5e, 0x0c,
	0xad, 0x17, 0xf7, 0x4f, 0x03, 0x7a, 0xa7, 0x22, 0x89, 0x7c, 0x5b, 0xbc, 0x2b, 0x9b, 0x34, 0xd4,
	0x26, 0xd5, 0x33, 0x6f, 0x68, 0x67, 0xee, 0x40, 0x7b, 0x16, 0x50, 0x7a, 0x9b, 0x66, 0x51, 0xb1,
	0x60, 0x85, 0xac, 0x5e, 0xf1, 0xfa, 0x43, 0x57, 0xec, 0x8e, 0xa1, 0x77, 0x21, 0x1a, 0xd3, 0x4a,
	0x5a, 0xdd, 0x8a, 0x9a, 0xa3, 0xf9, 0x60, 0x8e, 0x27, 0xd0, 0xd7, 0x72, 0xd0, 0x59, 0x9a, 0x50,
	0xec, 0xfe, 0x08, 0x4f, 0x4e, 0xaf, 0x70, 0x78, 0x7d, 0x9a, 0xe1, 0x08, 0x27, 0x8c, 0x04, 0x31,
	0x55, 0x20, 0x11, 0x07, 0x5a, 0x40, 0x22, 0x84, 0x4a, 0xdb, 0x8d, 0x6a, 0xdb, 0xee, 0x21, 0xf4,
	0x5f, 0xa6, 0xd9, 0x24, 0x65, 0xe7, 0x52, 0xb3, 0x12, 0x5d, 0xd7, 0x86, 0x6d, 0xdd, 0x5d, 0x56,
	0xf5, 0x0d, 0x6c, 0x8b, 0xaa, 0x3c, 0x4c, 0x31, 0xfb, 0x39, 0xbd, 0xc6, 0x49, 0x11, 0x69, 0x1f,
	0xac, 0x8c, 0x2b, 0x7d, 0xc6, 0xb5, 0x32, 0x1e, 0x64, 0xa5, 0x9f, 0xfb, 0x85, 0x6c, 0x48, 0x7d,
	0x9a, 0x47, 0x45, 0x4f, 0xa1, 0xcd, 0x57, 0x36, 0x88, 0x25, 0x9c, 0x6d, 0xaf, 0x45, 0xe8, 0x1b,
	0x2e, 0xba, 0x6f, 0xa1, 0x27, 0x1e, 0xe8, 0x85, 0x3f, 0x94, 0x8e, 0xb3, 0x5d, 0x82, 0x6f, 0x7d,
	0x0d, 0x12, 0x2b, 0xc1, 0xb7, 0x45, 0x28, 0x8e, 0xbd, 0x16, 0x5b, 0x76, 0x39, 0x2f, 0x86, 0xa2,
	0x67, 0x7d, 0x60, 0xf2, 0x2b, 0x46, 0xb0, 0x54, 0x4f, 0x73, 0xb9, 0x1e, 0x1b, 0xb6, 0xf5, 0xb4,
	0xb2, 0xa0, 0x4f, 0x00, 0x89, 0xf3, 0xbd, 0x13, 0x3c, 0xa1, 0x0c, 0x4f, 0xed, 0x3e, 0x17, 0xdc,
	0x3e, 0x3c, 0xae, 0xf8, 0xca, 0x10, 0x9f, 0xc1, 0x53, 0xde, 0x6c, 0x12, 0xe5, 0x3c, 0x10, 0x06,
	0x8c, 0xa4, 0xc9, 0xea, 0x35, 0xd8, 0x05, 0xa7, 0xee, 0x89, 0x0c, 0xf8, 0x25, 0xf4, 0x4e, 0xc5,
	0xa7, 0xe3, 0x9d, 0xae, 0x83, 0x83, 0xae, 0x3d, 0x93, 0xf1, 0x4e, 0xa0, 0x27, 0xf6, 0xe3, 0x42,
	0xde, 0x71, 0x11, 0x4f, 0x3d, 0x75, 0xa3, 0x7a, 0xea, 0xee, 0xb7, 0xd0, 0xd7, 0xde, 0xc8, 0x8d,
	0x1a, 0xc2, 0x16, 0xa1, 0x7e, 0x70, 0x13, 0x90, 0x38, 0x18, 0xc7, 0x58, 0x6e, 0x95, 0x45, 0xe8,
	0xa8, 0x50, 0xb9, 0x1f, 0xc3, 0x23, 0xf1, 0x56, 0x87, 0xb4, 0x06, 0x88, 0xaf, 0x01, 0xa9, 0xae,
	0xff, 0x3b, 0xc7, 0xc9, 0xbf, 0x2d, 0xe8, 0xca, 0x3e, 0x7f, 0xca, 0xff, 0xcc, 0x41, 0x2f, 0xa0,
	0x53, 0xe1, 0x39, 0xf4, 0xc1, 0x82, 0x1d, 0xea, 0x08, 0xd0, 0x51, 0xd8, 0x43, 0x5a, 0xdc, 0x35,
	0xe4, 0x41, 0xa7, 0xd2, 0x78, 0x25, 0x4a, 0x0d, 0x8a, 0xce, 0xfe, 0xbd, 0x76, 0x09, 0xff, 0x1a,
	0x3a, 0x03, 0x58, 0x74, 0x89, 0x76, 0xb4, 0x07, 0x2a, 0x4c, 0xce, 0x6e, 0xbd, 0xb1, 0x0c, 0xf5,
	0x03, 0xbc, 0xaf, 0x93, 0x17, 0x1a, 0x6a, 0x6f, 0x96, 0x89, 0xad, 0xbe, 0xd5, 0x5f, 0xe0, 0x3d,
	0x8d, 0x37, 0xd0, 0x40, 0x0b, 0xb5, 0xc4, 0x46, 0xce, 0x70, 0x85, 0x47, 0x59, 0xe5, 0x4b, 0xe8,
	0x56, 0xbf, 0x55, 0x48, 0x41, 0xa9, 0xf6, 0x2b, 0x56, 0x5f, 0xe1, 0x05, 0x74, 0xab, 0x74, 0xa9,
	0xc6, 0xa9, 0xe5, 0x5d, 0x67, 0x70, 0xbf, 0x43, 0x59, 0x9e, 0x07, 0x9d, 0x0a, 0x3d, 0xa9, 0x33,
	0xae, 0xe3, 0x44, 0x75, 0xc6, 0xf5, 0xbc, 0x26, 0x4a, 0xad, 0x52, 0x8c, 0x5a, 0x6a, 0x2d, 0xe7,
	0xa9, 0xa5, 0xde, 0xc3, 0x4e, 0x6b, 0xe8, 0x15, 0x58, 0x0a, 0xe7, 0x20, 0x65, 0x3d, 0x96, 0x69,
	0xcb, 0xd9, 0xbb, 0xc7, 0x5a, 0x46, 0x0b, 0x00, 0x2d, 0xf3, 0x0e, 0x7a, 0x56, 0xed, 0xae, 0x96,
	0xc8, 0x9c, 0x0f, 0x57, 0x3b, 0xa9, 0xd8, 0x56, 0x58, 0xa8, 0x72, 0x3f, 0x35, 0xac, 0x56, 0xb9,
	0x9f, 0x5a, 0xfa, 0x5a, 0x7b, 0xfe, 0xec, 0xed, 0x70, 0x42, 0xd8, 0xd5, 0x7c, 0x7c, 0x14, 0xa6,
	0xd3, 0xe3, 0xdc, 0xfd, 0x90, 0xa4, 0xc7, 0xf9, 0xbf, 0x3b, 0x93, 0x34, 0x0e, 0x92, 0xc9, 0x78,
	0x53, 0x48, 0x9f, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x2a, 0x97, 0xbc, 0x05, 0x0d, 0x00,
	0x00,
}
