// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth-service.proto

package golang // import "github.com/metrix-io/proto/golang"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{1}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (dst *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(dst, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{2}
}
func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (dst *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(dst, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type LogoutAllRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutAllRequest) Reset()         { *m = LogoutAllRequest{} }
func (m *LogoutAllRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutAllRequest) ProtoMessage()    {}
func (*LogoutAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{3}
}
func (m *LogoutAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutAllRequest.Unmarshal(m, b)
}
func (m *LogoutAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutAllRequest.Marshal(b, m, deterministic)
}
func (dst *LogoutAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutAllRequest.Merge(dst, src)
}
func (m *LogoutAllRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutAllRequest.Size(m)
}
func (m *LogoutAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutAllRequest proto.InternalMessageInfo

func (m *LogoutAllRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type LogoutAllResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutAllResponse) Reset()         { *m = LogoutAllResponse{} }
func (m *LogoutAllResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutAllResponse) ProtoMessage()    {}
func (*LogoutAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{4}
}
func (m *LogoutAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutAllResponse.Unmarshal(m, b)
}
func (m *LogoutAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutAllResponse.Marshal(b, m, deterministic)
}
func (dst *LogoutAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutAllResponse.Merge(dst, src)
}
func (m *LogoutAllResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutAllResponse.Size(m)
}
func (m *LogoutAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutAllResponse proto.InternalMessageInfo

type AccessToken struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Subject     string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// The lifetime of the access token in seconds.
	ExpiresIn int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// Unix timestamp when token expires.
	ExpiresAt            int64    `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{5}
}
func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (dst *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(dst, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccessToken) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AccessToken) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *AccessToken) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

// *
// A permission specifies a set of operations for a given resource.
//
// A resource name starts with an "mtx:"-prefix followed by a resource identifier
// usually in the form of "mtx:<resource>:<id>:<subresource>:<subid>".
type Permission struct {
	Resource             string   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Operations           []string `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{6}
}
func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (dst *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(dst, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *Permission) GetOperations() []string {
	if m != nil {
		return m.Operations
	}
	return nil
}

type PermissionAssignments struct {
	Subject              string        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PermissionAssignments) Reset()         { *m = PermissionAssignments{} }
func (m *PermissionAssignments) String() string { return proto.CompactTextString(m) }
func (*PermissionAssignments) ProtoMessage()    {}
func (*PermissionAssignments) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{7}
}
func (m *PermissionAssignments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionAssignments.Unmarshal(m, b)
}
func (m *PermissionAssignments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionAssignments.Marshal(b, m, deterministic)
}
func (dst *PermissionAssignments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionAssignments.Merge(dst, src)
}
func (m *PermissionAssignments) XXX_Size() int {
	return xxx_messageInfo_PermissionAssignments.Size(m)
}
func (m *PermissionAssignments) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionAssignments.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionAssignments proto.InternalMessageInfo

func (m *PermissionAssignments) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *PermissionAssignments) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type GrantPermissionsRequest struct {
	Subject              string        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GrantPermissionsRequest) Reset()         { *m = GrantPermissionsRequest{} }
func (m *GrantPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GrantPermissionsRequest) ProtoMessage()    {}
func (*GrantPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{8}
}
func (m *GrantPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPermissionsRequest.Unmarshal(m, b)
}
func (m *GrantPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *GrantPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPermissionsRequest.Merge(dst, src)
}
func (m *GrantPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GrantPermissionsRequest.Size(m)
}
func (m *GrantPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPermissionsRequest proto.InternalMessageInfo

func (m *GrantPermissionsRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *GrantPermissionsRequest) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type GrantPermissionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantPermissionsResponse) Reset()         { *m = GrantPermissionsResponse{} }
func (m *GrantPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GrantPermissionsResponse) ProtoMessage()    {}
func (*GrantPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{9}
}
func (m *GrantPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPermissionsResponse.Unmarshal(m, b)
}
func (m *GrantPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *GrantPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPermissionsResponse.Merge(dst, src)
}
func (m *GrantPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GrantPermissionsResponse.Size(m)
}
func (m *GrantPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPermissionsResponse proto.InternalMessageInfo

type RevokePermissionsRequest struct {
	Subject              string        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RevokePermissionsRequest) Reset()         { *m = RevokePermissionsRequest{} }
func (m *RevokePermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*RevokePermissionsRequest) ProtoMessage()    {}
func (*RevokePermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{10}
}
func (m *RevokePermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePermissionsRequest.Unmarshal(m, b)
}
func (m *RevokePermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *RevokePermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePermissionsRequest.Merge(dst, src)
}
func (m *RevokePermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_RevokePermissionsRequest.Size(m)
}
func (m *RevokePermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePermissionsRequest proto.InternalMessageInfo

func (m *RevokePermissionsRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *RevokePermissionsRequest) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type RevokePermissionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePermissionsResponse) Reset()         { *m = RevokePermissionsResponse{} }
func (m *RevokePermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*RevokePermissionsResponse) ProtoMessage()    {}
func (*RevokePermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{11}
}
func (m *RevokePermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePermissionsResponse.Unmarshal(m, b)
}
func (m *RevokePermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *RevokePermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePermissionsResponse.Merge(dst, src)
}
func (m *RevokePermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_RevokePermissionsResponse.Size(m)
}
func (m *RevokePermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePermissionsResponse proto.InternalMessageInfo

type GetPermissionsRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermissionsRequest) Reset()         { *m = GetPermissionsRequest{} }
func (m *GetPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPermissionsRequest) ProtoMessage()    {}
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{12}
}
func (m *GetPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionsRequest.Unmarshal(m, b)
}
func (m *GetPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *GetPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionsRequest.Merge(dst, src)
}
func (m *GetPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPermissionsRequest.Size(m)
}
func (m *GetPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionsRequest proto.InternalMessageInfo

func (m *GetPermissionsRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type HasPermissionsRequest struct {
	Subject              string        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HasPermissionsRequest) Reset()         { *m = HasPermissionsRequest{} }
func (m *HasPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*HasPermissionsRequest) ProtoMessage()    {}
func (*HasPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{13}
}
func (m *HasPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasPermissionsRequest.Unmarshal(m, b)
}
func (m *HasPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasPermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *HasPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasPermissionsRequest.Merge(dst, src)
}
func (m *HasPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_HasPermissionsRequest.Size(m)
}
func (m *HasPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasPermissionsRequest proto.InternalMessageInfo

func (m *HasPermissionsRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *HasPermissionsRequest) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type HasPermissionsResponse struct {
	HasPermissions       bool          `protobuf:"varint,1,opt,name=has_permissions,json=hasPermissions,proto3" json:"has_permissions,omitempty"`
	MissingPermissions   []*Permission `protobuf:"bytes,2,rep,name=missing_permissions,json=missingPermissions,proto3" json:"missing_permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HasPermissionsResponse) Reset()         { *m = HasPermissionsResponse{} }
func (m *HasPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*HasPermissionsResponse) ProtoMessage()    {}
func (*HasPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{14}
}
func (m *HasPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasPermissionsResponse.Unmarshal(m, b)
}
func (m *HasPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasPermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *HasPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasPermissionsResponse.Merge(dst, src)
}
func (m *HasPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_HasPermissionsResponse.Size(m)
}
func (m *HasPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasPermissionsResponse proto.InternalMessageInfo

func (m *HasPermissionsResponse) GetHasPermissions() bool {
	if m != nil {
		return m.HasPermissions
	}
	return false
}

func (m *HasPermissionsResponse) GetMissingPermissions() []*Permission {
	if m != nil {
		return m.MissingPermissions
	}
	return nil
}

type InheritPermissionsRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ParentSubject        string   `protobuf:"bytes,2,opt,name=parent_subject,json=parentSubject,proto3" json:"parent_subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InheritPermissionsRequest) Reset()         { *m = InheritPermissionsRequest{} }
func (m *InheritPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*InheritPermissionsRequest) ProtoMessage()    {}
func (*InheritPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{15}
}
func (m *InheritPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InheritPermissionsRequest.Unmarshal(m, b)
}
func (m *InheritPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InheritPermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *InheritPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InheritPermissionsRequest.Merge(dst, src)
}
func (m *InheritPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_InheritPermissionsRequest.Size(m)
}
func (m *InheritPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InheritPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InheritPermissionsRequest proto.InternalMessageInfo

func (m *InheritPermissionsRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *InheritPermissionsRequest) GetParentSubject() string {
	if m != nil {
		return m.ParentSubject
	}
	return ""
}

type InheritPermissionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InheritPermissionsResponse) Reset()         { *m = InheritPermissionsResponse{} }
func (m *InheritPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*InheritPermissionsResponse) ProtoMessage()    {}
func (*InheritPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{16}
}
func (m *InheritPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InheritPermissionsResponse.Unmarshal(m, b)
}
func (m *InheritPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InheritPermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *InheritPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InheritPermissionsResponse.Merge(dst, src)
}
func (m *InheritPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_InheritPermissionsResponse.Size(m)
}
func (m *InheritPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InheritPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InheritPermissionsResponse proto.InternalMessageInfo

type DisinheritPermissionsRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ParentSubject        string   `protobuf:"bytes,2,opt,name=parent_subject,json=parentSubject,proto3" json:"parent_subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisinheritPermissionsRequest) Reset()         { *m = DisinheritPermissionsRequest{} }
func (m *DisinheritPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*DisinheritPermissionsRequest) ProtoMessage()    {}
func (*DisinheritPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{17}
}
func (m *DisinheritPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisinheritPermissionsRequest.Unmarshal(m, b)
}
func (m *DisinheritPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisinheritPermissionsRequest.Marshal(b, m, deterministic)
}
func (dst *DisinheritPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisinheritPermissionsRequest.Merge(dst, src)
}
func (m *DisinheritPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_DisinheritPermissionsRequest.Size(m)
}
func (m *DisinheritPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisinheritPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisinheritPermissionsRequest proto.InternalMessageInfo

func (m *DisinheritPermissionsRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *DisinheritPermissionsRequest) GetParentSubject() string {
	if m != nil {
		return m.ParentSubject
	}
	return ""
}

type DisinheritPermissionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisinheritPermissionsResponse) Reset()         { *m = DisinheritPermissionsResponse{} }
func (m *DisinheritPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*DisinheritPermissionsResponse) ProtoMessage()    {}
func (*DisinheritPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{18}
}
func (m *DisinheritPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisinheritPermissionsResponse.Unmarshal(m, b)
}
func (m *DisinheritPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisinheritPermissionsResponse.Marshal(b, m, deterministic)
}
func (dst *DisinheritPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisinheritPermissionsResponse.Merge(dst, src)
}
func (m *DisinheritPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_DisinheritPermissionsResponse.Size(m)
}
func (m *DisinheritPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisinheritPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisinheritPermissionsResponse proto.InternalMessageInfo

type DeleteSubjectRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubjectRequest) Reset()         { *m = DeleteSubjectRequest{} }
func (m *DeleteSubjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSubjectRequest) ProtoMessage()    {}
func (*DeleteSubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{19}
}
func (m *DeleteSubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubjectRequest.Unmarshal(m, b)
}
func (m *DeleteSubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubjectRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubjectRequest.Merge(dst, src)
}
func (m *DeleteSubjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSubjectRequest.Size(m)
}
func (m *DeleteSubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubjectRequest proto.InternalMessageInfo

func (m *DeleteSubjectRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type DeleteSubjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubjectResponse) Reset()         { *m = DeleteSubjectResponse{} }
func (m *DeleteSubjectResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSubjectResponse) ProtoMessage()    {}
func (*DeleteSubjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_272370d608642cb5, []int{20}
}
func (m *DeleteSubjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubjectResponse.Unmarshal(m, b)
}
func (m *DeleteSubjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubjectResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteSubjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubjectResponse.Merge(dst, src)
}
func (m *DeleteSubjectResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSubjectResponse.Size(m)
}
func (m *DeleteSubjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubjectResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "metrixio.LoginRequest")
	proto.RegisterType((*LogoutRequest)(nil), "metrixio.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "metrixio.LogoutResponse")
	proto.RegisterType((*LogoutAllRequest)(nil), "metrixio.LogoutAllRequest")
	proto.RegisterType((*LogoutAllResponse)(nil), "metrixio.LogoutAllResponse")
	proto.RegisterType((*AccessToken)(nil), "metrixio.AccessToken")
	proto.RegisterType((*Permission)(nil), "metrixio.Permission")
	proto.RegisterType((*PermissionAssignments)(nil), "metrixio.PermissionAssignments")
	proto.RegisterType((*GrantPermissionsRequest)(nil), "metrixio.GrantPermissionsRequest")
	proto.RegisterType((*GrantPermissionsResponse)(nil), "metrixio.GrantPermissionsResponse")
	proto.RegisterType((*RevokePermissionsRequest)(nil), "metrixio.RevokePermissionsRequest")
	proto.RegisterType((*RevokePermissionsResponse)(nil), "metrixio.RevokePermissionsResponse")
	proto.RegisterType((*GetPermissionsRequest)(nil), "metrixio.GetPermissionsRequest")
	proto.RegisterType((*HasPermissionsRequest)(nil), "metrixio.HasPermissionsRequest")
	proto.RegisterType((*HasPermissionsResponse)(nil), "metrixio.HasPermissionsResponse")
	proto.RegisterType((*InheritPermissionsRequest)(nil), "metrixio.InheritPermissionsRequest")
	proto.RegisterType((*InheritPermissionsResponse)(nil), "metrixio.InheritPermissionsResponse")
	proto.RegisterType((*DisinheritPermissionsRequest)(nil), "metrixio.DisinheritPermissionsRequest")
	proto.RegisterType((*DisinheritPermissionsResponse)(nil), "metrixio.DisinheritPermissionsResponse")
	proto.RegisterType((*DeleteSubjectRequest)(nil), "metrixio.DeleteSubjectRequest")
	proto.RegisterType((*DeleteSubjectResponse)(nil), "metrixio.DeleteSubjectResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	// *
	// LoginR returns an access token if the login credentials
	// are valid. The login field may contain either a username or email
	// address.
	//
	// Errors:
	// - UNAUTHENTICATED if the call credentials are invalid.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AccessToken, error)
	// *
	// Logout removes the access token used to authenticate the request with.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// *
	// LogoutAll removes all access tokens associated with a subject.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges
	//   to delete an access tokens for given subject.
	LogoutAll(ctx context.Context, in *LogoutAllRequest, opts ...grpc.CallOption) (*LogoutAllResponse, error)
	// *
	// CreatePermission adds one or more permissions to a subject.
	//
	// A subject can either be a user account, organization, role or other and must
	// be a valid resource name, e.g. "mtx:account:g921sdfb1lkg".
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges
	//   to read subject's permissions.
	GrantPermissions(ctx context.Context, in *GrantPermissionsRequest, opts ...grpc.CallOption) (*PermissionAssignments, error)
	// *
	// Returns all permissions for the specified subject.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges
	//   to read subject's permissions.
	GetPermissions(ctx context.Context, in *GetPermissionsRequest, opts ...grpc.CallOption) (*PermissionAssignments, error)
	// *
	// Checks if the subjects has specified permission(s). Returns a list of
	// all permissions that subject is missing.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges
	//   to read subject's permissions.
	HasPermissions(ctx context.Context, in *HasPermissionsRequest, opts ...grpc.CallOption) (*HasPermissionsResponse, error)
	// *
	// RevokePermissionsRequest removes one or more permissions from a subject.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges to
	//   revoke subject's permissions.
	RevokePermissions(ctx context.Context, in *RevokePermissionsRequest, opts ...grpc.CallOption) (*RevokePermissionsRequest, error)
	// *
	// DeleteSubject removes any permissions associated with the subject.
	//
	// It also removes any permission inheritance relationships, including those
	// which inherit from the subject being deleted.
	//
	// If the subject being deleted does not have any registered permissions the
	// request will still be deemed successful.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges to
	//   delete this subject.
	DeleteSubject(ctx context.Context, in *DeleteSubjectRequest, opts ...grpc.CallOption) (*DeleteSubjectResponse, error)
	// *
	// InheritPermissions establishes a permission inheritance relationship
	// between two subjects. A common example is a user account being part of
	// a group.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject does not have permission to grant
	//   permissions to the parent subject.
	// - NOT_FOUND if no inheritance relationship exists between specified subjects.
	InheritPermissions(ctx context.Context, in *InheritPermissionsRequest, opts ...grpc.CallOption) (*InheritPermissionsResponse, error)
	// *
	// DisinheritPermissions removes any inheritance relationship between two
	// subjects.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject does not have permission to revoke
	//   permissions of the parent subject.
	// - NOT_FOUND if no inheritance relationship exists between specified subjects.
	DisinheritPermissions(ctx context.Context, in *DisinheritPermissionsRequest, opts ...grpc.CallOption) (*DisinheritPermissionsResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LogoutAll(ctx context.Context, in *LogoutAllRequest, opts ...grpc.CallOption) (*LogoutAllResponse, error) {
	out := new(LogoutAllResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/LogoutAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GrantPermissions(ctx context.Context, in *GrantPermissionsRequest, opts ...grpc.CallOption) (*PermissionAssignments, error) {
	out := new(PermissionAssignments)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/GrantPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetPermissions(ctx context.Context, in *GetPermissionsRequest, opts ...grpc.CallOption) (*PermissionAssignments, error) {
	out := new(PermissionAssignments)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/GetPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) HasPermissions(ctx context.Context, in *HasPermissionsRequest, opts ...grpc.CallOption) (*HasPermissionsResponse, error) {
	out := new(HasPermissionsResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/HasPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokePermissions(ctx context.Context, in *RevokePermissionsRequest, opts ...grpc.CallOption) (*RevokePermissionsRequest, error) {
	out := new(RevokePermissionsRequest)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/RevokePermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteSubject(ctx context.Context, in *DeleteSubjectRequest, opts ...grpc.CallOption) (*DeleteSubjectResponse, error) {
	out := new(DeleteSubjectResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/DeleteSubject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) InheritPermissions(ctx context.Context, in *InheritPermissionsRequest, opts ...grpc.CallOption) (*InheritPermissionsResponse, error) {
	out := new(InheritPermissionsResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/InheritPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DisinheritPermissions(ctx context.Context, in *DisinheritPermissionsRequest, opts ...grpc.CallOption) (*DisinheritPermissionsResponse, error) {
	out := new(DisinheritPermissionsResponse)
	err := c.cc.Invoke(ctx, "/metrixio.AuthService/DisinheritPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	// *
	// LoginR returns an access token if the login credentials
	// are valid. The login field may contain either a username or email
	// address.
	//
	// Errors:
	// - UNAUTHENTICATED if the call credentials are invalid.
	Login(context.Context, *LoginRequest) (*AccessToken, error)
	// *
	// Logout removes the access token used to authenticate the request with.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// *
	// LogoutAll removes all access tokens associated with a subject.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges
	//   to delete an access tokens for given subject.
	LogoutAll(context.Context, *LogoutAllRequest) (*LogoutAllResponse, error)
	// *
	// CreatePermission adds one or more permissions to a subject.
	//
	// A subject can either be a user account, organization, role or other and must
	// be a valid resource name, e.g. "mtx:account:g921sdfb1lkg".
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges
	//   to read subject's permissions.
	GrantPermissions(context.Context, *GrantPermissionsRequest) (*PermissionAssignments, error)
	// *
	// Returns all permissions for the specified subject.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges
	//   to read subject's permissions.
	GetPermissions(context.Context, *GetPermissionsRequest) (*PermissionAssignments, error)
	// *
	// Checks if the subjects has specified permission(s). Returns a list of
	// all permissions that subject is missing.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges
	//   to read subject's permissions.
	HasPermissions(context.Context, *HasPermissionsRequest) (*HasPermissionsResponse, error)
	// *
	// RevokePermissionsRequest removes one or more permissions from a subject.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges to
	//   revoke subject's permissions.
	RevokePermissions(context.Context, *RevokePermissionsRequest) (*RevokePermissionsRequest, error)
	// *
	// DeleteSubject removes any permissions associated with the subject.
	//
	// It also removes any permission inheritance relationships, including those
	// which inherit from the subject being deleted.
	//
	// If the subject being deleted does not have any registered permissions the
	// request will still be deemed successful.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject has insufficient privileges to
	//   delete this subject.
	DeleteSubject(context.Context, *DeleteSubjectRequest) (*DeleteSubjectResponse, error)
	// *
	// InheritPermissions establishes a permission inheritance relationship
	// between two subjects. A common example is a user account being part of
	// a group.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject does not have permission to grant
	//   permissions to the parent subject.
	// - NOT_FOUND if no inheritance relationship exists between specified subjects.
	InheritPermissions(context.Context, *InheritPermissionsRequest) (*InheritPermissionsResponse, error)
	// *
	// DisinheritPermissions removes any inheritance relationship between two
	// subjects.
	//
	// Errors:
	// - PERMISSION_DENIED if the logged in subject does not have permission to revoke
	//   permissions of the parent subject.
	// - NOT_FOUND if no inheritance relationship exists between specified subjects.
	DisinheritPermissions(context.Context, *DisinheritPermissionsRequest) (*DisinheritPermissionsResponse, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LogoutAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LogoutAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/LogoutAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LogoutAll(ctx, req.(*LogoutAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GrantPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GrantPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/GrantPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GrantPermissions(ctx, req.(*GrantPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/GetPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetPermissions(ctx, req.(*GetPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_HasPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).HasPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/HasPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).HasPermissions(ctx, req.(*HasPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/RevokePermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokePermissions(ctx, req.(*RevokePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/DeleteSubject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteSubject(ctx, req.(*DeleteSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_InheritPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InheritPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).InheritPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/InheritPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).InheritPermissions(ctx, req.(*InheritPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DisinheritPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisinheritPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DisinheritPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.AuthService/DisinheritPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DisinheritPermissions(ctx, req.(*DisinheritPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metrixio.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "LogoutAll",
			Handler:    _AuthService_LogoutAll_Handler,
		},
		{
			MethodName: "GrantPermissions",
			Handler:    _AuthService_GrantPermissions_Handler,
		},
		{
			MethodName: "GetPermissions",
			Handler:    _AuthService_GetPermissions_Handler,
		},
		{
			MethodName: "HasPermissions",
			Handler:    _AuthService_HasPermissions_Handler,
		},
		{
			MethodName: "RevokePermissions",
			Handler:    _AuthService_RevokePermissions_Handler,
		},
		{
			MethodName: "DeleteSubject",
			Handler:    _AuthService_DeleteSubject_Handler,
		},
		{
			MethodName: "InheritPermissions",
			Handler:    _AuthService_InheritPermissions_Handler,
		},
		{
			MethodName: "DisinheritPermissions",
			Handler:    _AuthService_DisinheritPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth-service.proto",
}

func init() {
	proto.RegisterFile("proto/auth-service.proto", fileDescriptor_auth_service_272370d608642cb5)
}

var fileDescriptor_auth_service_272370d608642cb5 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0x4d, 0xe0, 0x83, 0x8f, 0x4c, 0x20, 0xc0, 0x40, 0xc0, 0x98, 0xbf, 0xb0, 0xb4, 0x25, 0x17,
	0x25, 0xb4, 0x54, 0xaa, 0x7a, 0x53, 0xa9, 0xa9, 0x68, 0x01, 0x89, 0x8b, 0xca, 0x50, 0xa9, 0xaa,
	0x5a, 0x45, 0x26, 0x5d, 0x25, 0x0b, 0xc9, 0xae, 0xeb, 0x5d, 0x53, 0x1e, 0x81, 0x37, 0xec, 0xeb,
	0x54, 0xb1, 0x37, 0xf6, 0x3a, 0x71, 0xf8, 0xa9, 0x54, 0xee, 0x32, 0xb3, 0x73, 0xce, 0x99, 0xec,
	0xce, 0x1c, 0x19, 0x2c, 0xcf, 0x17, 0x4a, 0xec, 0xb9, 0x81, 0x6a, 0xef, 0x4a, 0xea, 0x5f, 0xb1,
	0x26, 0xad, 0x85, 0x29, 0x9c, 0xea, 0x52, 0xe5, 0xb3, 0x6b, 0x26, 0xc8, 0x3b, 0x98, 0x3e, 0x11,
	0x2d, 0xc6, 0x1d, 0xfa, 0x33, 0xa0, 0x52, 0xe1, 0x22, 0x4c, 0x74, 0x7a, 0xb1, 0x95, 0xaf, 0xe4,
	0xab, 0x05, 0x27, 0x0a, 0xd0, 0x86, 0x29, 0xcf, 0x95, 0xf2, 0x97, 0xf0, 0x7f, 0x58, 0x63, 0xe1,
	0x41, 0x1c, 0x93, 0x59, 0x98, 0x39, 0x11, 0x2d, 0x11, 0x28, 0x4d, 0x41, 0xe6, 0xa0, 0xd4, 0x4f,
	0x48, 0x4f, 0x70, 0x49, 0xc9, 0x73, 0x98, 0x8b, 0x32, 0xf5, 0x4e, 0xa7, 0x2f, 0x64, 0xc1, 0xff,
	0x32, 0x38, 0xbf, 0xa0, 0x4d, 0xa5, 0xa5, 0xfa, 0x21, 0x59, 0x80, 0x79, 0xa3, 0x5a, 0x53, 0xdc,
	0xe4, 0xa1, 0x58, 0x6f, 0x36, 0xa9, 0x94, 0x67, 0xe2, 0x92, 0x72, 0xdc, 0x82, 0x69, 0x37, 0x0c,
	0x1b, 0xaa, 0x17, 0x6b, 0x8e, 0xa2, 0x6b, 0x94, 0x18, 0x0a, 0x63, 0x29, 0x05, 0x5c, 0x07, 0xa0,
	0xd7, 0x1e, 0xf3, 0xa9, 0x6c, 0x30, 0x6e, 0x8d, 0x57, 0xf2, 0xd5, 0x09, 0xa7, 0xa0, 0x33, 0xc7,
	0xdc, 0x3c, 0x76, 0x95, 0xf5, 0x5f, 0x25, 0x5f, 0x1d, 0x8f, 0x8f, 0xeb, 0x8a, 0x1c, 0x01, 0x7c,
	0xa2, 0x7e, 0x97, 0x49, 0xc9, 0x44, 0x78, 0x35, 0x3e, 0x95, 0x22, 0xf0, 0x9b, 0x54, 0x37, 0x11,
	0xc7, 0xb8, 0x01, 0x20, 0x3c, 0xea, 0xbb, 0x8a, 0x09, 0x2e, 0xad, 0xb1, 0xca, 0x78, 0xb5, 0xe0,
	0x18, 0x19, 0xc2, 0xa0, 0x9c, 0x30, 0xd5, 0xa5, 0x64, 0x2d, 0xde, 0xa5, 0x5c, 0xc9, 0xd1, 0x97,
	0x83, 0xaf, 0xa1, 0xe8, 0xc5, 0x90, 0x88, 0xb3, 0xb8, 0xbf, 0x58, 0xeb, 0xbf, 0x67, 0x2d, 0xe1,
	0x73, 0xcc, 0x42, 0x72, 0x09, 0xcb, 0x87, 0xbe, 0xcb, 0x55, 0x72, 0x2e, 0xef, 0x7c, 0x89, 0xbf,
	0x16, 0xb3, 0xc1, 0x1a, 0x16, 0xd3, 0x0f, 0xd9, 0x01, 0xcb, 0xa1, 0x57, 0xe2, 0x92, 0x3e, 0x4a,
	0x27, 0xab, 0xb0, 0x92, 0xa1, 0xa6, 0x5b, 0x79, 0x09, 0xe5, 0x43, 0xfa, 0xa0, 0x1b, 0xe9, 0xbd,
	0xd8, 0x91, 0x2b, 0x1f, 0xa5, 0xf5, 0x9b, 0x3c, 0x2c, 0x0d, 0x6a, 0x45, 0x8d, 0xe3, 0x0e, 0xcc,
	0xb6, 0x5d, 0xd9, 0x30, 0x69, 0x7b, 0xa2, 0x53, 0x4e, 0xa9, 0x9d, 0x02, 0xe0, 0x07, 0x58, 0x08,
	0x7f, 0xf3, 0x56, 0xe3, 0xbe, 0x3d, 0xa0, 0x06, 0x18, 0x34, 0xe4, 0x1b, 0xac, 0x1c, 0xf3, 0x36,
	0xf5, 0xd9, 0xc3, 0xc6, 0xe7, 0x29, 0x94, 0x3c, 0xd7, 0xa7, 0x5c, 0x35, 0xd2, 0x7b, 0x38, 0x13,
	0x65, 0x4f, 0xf5, 0x9d, 0xae, 0x81, 0x9d, 0xc5, 0xae, 0x1f, 0xa9, 0x01, 0x6b, 0x07, 0x4c, 0xb2,
	0x7f, 0x27, 0xbf, 0x09, 0xeb, 0x23, 0x04, 0x74, 0x07, 0x2f, 0x60, 0xf1, 0x80, 0x76, 0xa8, 0xa2,
	0x1a, 0x71, 0xf7, 0x94, 0x2c, 0x43, 0x79, 0x00, 0x11, 0x51, 0xed, 0xff, 0x9e, 0x84, 0x62, 0x3d,
	0x50, 0xed, 0xd3, 0xc8, 0x8d, 0xf1, 0x0d, 0x4c, 0x84, 0xee, 0x8b, 0x4b, 0xc9, 0x5b, 0x98, 0x76,
	0x6c, 0x97, 0x93, 0xbc, 0xe1, 0x7e, 0x24, 0x87, 0x6f, 0x61, 0x32, 0x32, 0x49, 0x5c, 0x4e, 0x41,
	0x13, 0x1f, 0xb6, 0xad, 0xe1, 0x03, 0xfd, 0x8f, 0x72, 0xf8, 0x11, 0x0a, 0xb1, 0xc7, 0xa2, 0x3d,
	0x58, 0x98, 0xd8, 0xb4, 0xbd, 0x9a, 0x79, 0x16, 0xf3, 0x7c, 0x81, 0xb9, 0xc1, 0x4d, 0xc7, 0xad,
	0x04, 0x32, 0xc2, 0x72, 0xec, 0xcd, 0xac, 0xd1, 0x33, 0x0c, 0x90, 0xe4, 0xf0, 0x0c, 0x4a, 0xe9,
	0xe5, 0x44, 0x03, 0x94, 0xb9, 0xb6, 0xf7, 0x61, 0xfd, 0x0c, 0xa5, 0xf4, 0x4e, 0x99, 0xac, 0x99,
	0x9b, 0x6d, 0x57, 0x46, 0x17, 0xc4, 0xd7, 0xf0, 0x1d, 0xe6, 0x87, 0x6c, 0x06, 0x49, 0x02, 0x1c,
	0xe5, 0x78, 0xf6, 0x3d, 0x6a, 0x48, 0x0e, 0x1d, 0x98, 0x49, 0xcd, 0x13, 0x6e, 0x24, 0xb0, 0xac,
	0xd1, 0x34, 0x6f, 0x22, 0x73, 0x10, 0x49, 0x0e, 0x5d, 0xc0, 0xe1, 0xad, 0xc3, 0xed, 0x04, 0x38,
	0x72, 0xe3, 0xed, 0x27, 0xb7, 0x17, 0xc5, 0x12, 0x17, 0x50, 0xce, 0xdc, 0x2c, 0x7c, 0x66, 0xb4,
	0x77, 0xcb, 0x6e, 0xdb, 0x3b, 0x77, 0xd6, 0xf5, 0xb5, 0xde, 0x6f, 0x7f, 0xdd, 0x6a, 0x31, 0xd5,
	0x0e, 0xce, 0x6b, 0x4d, 0xd1, 0xdd, 0x8b, 0x60, 0xbb, 0x4c, 0xec, 0x45, 0x9f, 0x40, 0x2d, 0xd1,
	0x71, 0x79, 0xeb, 0x7c, 0x32, 0x8c, 0x5e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x17, 0xf5, 0x06,
	0xdf, 0x19, 0x09, 0x00, 0x00,
}
