// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account-service.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrimaryEmail         string   `protobuf:"bytes,2,opt,name=primary_email,json=primaryEmail,proto3" json:"primary_email,omitempty"`
	IsVerified           bool     `protobuf:"varint,3,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{0}
}
func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (dst *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(dst, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountResponse) GetPrimaryEmail() string {
	if m != nil {
		return m.PrimaryEmail
	}
	return ""
}

func (m *AccountResponse) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

type GetByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdRequest) Reset()         { *m = GetByIdRequest{} }
func (m *GetByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIdRequest) ProtoMessage()    {}
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{1}
}
func (m *GetByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdRequest.Unmarshal(m, b)
}
func (m *GetByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdRequest.Merge(dst, src)
}
func (m *GetByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIdRequest.Size(m)
}
func (m *GetByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdRequest proto.InternalMessageInfo

func (m *GetByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByEmailRequest) Reset()         { *m = GetByEmailRequest{} }
func (m *GetByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetByEmailRequest) ProtoMessage()    {}
func (*GetByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{2}
}
func (m *GetByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByEmailRequest.Unmarshal(m, b)
}
func (m *GetByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByEmailRequest.Marshal(b, m, deterministic)
}
func (dst *GetByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByEmailRequest.Merge(dst, src)
}
func (m *GetByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetByEmailRequest.Size(m)
}
func (m *GetByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByEmailRequest proto.InternalMessageInfo

func (m *GetByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AuthenticateByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateByEmailRequest) Reset()         { *m = AuthenticateByEmailRequest{} }
func (m *AuthenticateByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateByEmailRequest) ProtoMessage()    {}
func (*AuthenticateByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{3}
}
func (m *AuthenticateByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateByEmailRequest.Unmarshal(m, b)
}
func (m *AuthenticateByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateByEmailRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateByEmailRequest.Merge(dst, src)
}
func (m *AuthenticateByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateByEmailRequest.Size(m)
}
func (m *AuthenticateByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateByEmailRequest proto.InternalMessageInfo

func (m *AuthenticateByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticateByEmailRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GeneratePasswordTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneratePasswordTokenRequest) Reset()         { *m = GeneratePasswordTokenRequest{} }
func (m *GeneratePasswordTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GeneratePasswordTokenRequest) ProtoMessage()    {}
func (*GeneratePasswordTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{4}
}
func (m *GeneratePasswordTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratePasswordTokenRequest.Unmarshal(m, b)
}
func (m *GeneratePasswordTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratePasswordTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GeneratePasswordTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratePasswordTokenRequest.Merge(dst, src)
}
func (m *GeneratePasswordTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GeneratePasswordTokenRequest.Size(m)
}
func (m *GeneratePasswordTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratePasswordTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratePasswordTokenRequest proto.InternalMessageInfo

func (m *GeneratePasswordTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GeneratePasswordTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneratePasswordTokenResponse) Reset()         { *m = GeneratePasswordTokenResponse{} }
func (m *GeneratePasswordTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GeneratePasswordTokenResponse) ProtoMessage()    {}
func (*GeneratePasswordTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{5}
}
func (m *GeneratePasswordTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratePasswordTokenResponse.Unmarshal(m, b)
}
func (m *GeneratePasswordTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratePasswordTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GeneratePasswordTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratePasswordTokenResponse.Merge(dst, src)
}
func (m *GeneratePasswordTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GeneratePasswordTokenResponse.Size(m)
}
func (m *GeneratePasswordTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratePasswordTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratePasswordTokenResponse proto.InternalMessageInfo

func (m *GeneratePasswordTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ChangePasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{6}
}
func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(dst, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyEmailRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{7}
}
func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(dst, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateAccountRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f9ac5b333fba7e6c, []int{8}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountResponse)(nil), "proto.AccountResponse")
	proto.RegisterType((*GetByIdRequest)(nil), "proto.GetByIdRequest")
	proto.RegisterType((*GetByEmailRequest)(nil), "proto.GetByEmailRequest")
	proto.RegisterType((*AuthenticateByEmailRequest)(nil), "proto.AuthenticateByEmailRequest")
	proto.RegisterType((*GeneratePasswordTokenRequest)(nil), "proto.GeneratePasswordTokenRequest")
	proto.RegisterType((*GeneratePasswordTokenResponse)(nil), "proto.GeneratePasswordTokenResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "proto.ChangePasswordRequest")
	proto.RegisterType((*VerifyEmailRequest)(nil), "proto.VerifyEmailRequest")
	proto.RegisterType((*CreateAccountRequest)(nil), "proto.CreateAccountRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	AuthenticateByEmail(ctx context.Context, in *AuthenticateByEmailRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	GeneratePasswordToken(ctx context.Context, in *GeneratePasswordTokenRequest, opts ...grpc.CallOption) (*GeneratePasswordTokenResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*AccountResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/GetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AuthenticateByEmail(ctx context.Context, in *AuthenticateByEmailRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/AuthenticateByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GeneratePasswordToken(ctx context.Context, in *GeneratePasswordTokenRequest, opts ...grpc.CallOption) (*GeneratePasswordTokenResponse, error) {
	out := new(GeneratePasswordTokenResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/GeneratePasswordToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/proto.AccountService/VerifyEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Create(context.Context, *CreateAccountRequest) (*AccountResponse, error)
	GetById(context.Context, *GetByIdRequest) (*AccountResponse, error)
	GetByEmail(context.Context, *GetByEmailRequest) (*AccountResponse, error)
	AuthenticateByEmail(context.Context, *AuthenticateByEmailRequest) (*AccountResponse, error)
	GeneratePasswordToken(context.Context, *GeneratePasswordTokenRequest) (*GeneratePasswordTokenResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*AccountResponse, error)
	VerifyEmail(context.Context, *VerifyEmailRequest) (*AccountResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetById(ctx, req.(*GetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/GetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetByEmail(ctx, req.(*GetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AuthenticateByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AuthenticateByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/AuthenticateByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AuthenticateByEmail(ctx, req.(*AuthenticateByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GeneratePasswordToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePasswordTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GeneratePasswordToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/GeneratePasswordToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GeneratePasswordToken(ctx, req.(*GeneratePasswordTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AccountService/VerifyEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _AccountService_GetById_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _AccountService_GetByEmail_Handler,
		},
		{
			MethodName: "AuthenticateByEmail",
			Handler:    _AccountService_AuthenticateByEmail_Handler,
		},
		{
			MethodName: "GeneratePasswordToken",
			Handler:    _AccountService_GeneratePasswordToken_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AccountService_ChangePassword_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _AccountService_VerifyEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account-service.proto",
}

func init() {
	proto.RegisterFile("account-service.proto", fileDescriptor_account_service_f9ac5b333fba7e6c)
}

var fileDescriptor_account_service_f9ac5b333fba7e6c = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x0b, 0x2d, 0x94, 0x0e, 0xad, 0xab, 0x6e, 0x71, 0xe5, 0xba, 0x54, 0xa5, 0xa6, 0x07,
	0x5a, 0xa9, 0x1c, 0xf2, 0xe7, 0x92, 0x4b, 0x02, 0x28, 0x02, 0x2e, 0x51, 0xe4, 0x44, 0xb9, 0xa2,
	0x8d, 0x3d, 0x81, 0x55, 0x82, 0xed, 0xec, 0x2e, 0x44, 0x3c, 0x49, 0x5e, 0x37, 0xc2, 0x5e, 0x3b,
	0x06, 0x6c, 0x2b, 0xca, 0xc9, 0x9a, 0x99, 0xef, 0x9b, 0x19, 0xcf, 0xfe, 0x40, 0xa7, 0x8e, 0xe3,
	0x2f, 0x3c, 0xf9, 0x5f, 0x20, 0x5f, 0x32, 0x07, 0xbb, 0x01, 0xf7, 0xa5, 0x4f, 0x2a, 0xe1, 0xc7,
	0x9a, 0xc2, 0xe7, 0x5e, 0x54, 0xb7, 0x51, 0x04, 0xbe, 0x27, 0x90, 0x68, 0x50, 0x66, 0xae, 0x51,
	0x6a, 0x95, 0x3a, 0x1f, 0xec, 0x32, 0x73, 0x49, 0x1b, 0x3e, 0x05, 0x9c, 0xcd, 0x29, 0x5f, 0x4d,
	0x70, 0x4e, 0xd9, 0x9d, 0x51, 0x0e, 0x4b, 0x1f, 0x55, 0xf2, 0x74, 0x9d, 0x23, 0xbf, 0xa0, 0xce,
	0xc4, 0x64, 0x89, 0x9c, 0xdd, 0x30, 0x74, 0x8d, 0xb7, 0xad, 0x52, 0xa7, 0x66, 0x03, 0x13, 0x57,
	0x2a, 0x63, 0xb5, 0x40, 0x1b, 0xa2, 0xec, 0xaf, 0xc6, 0xae, 0x8d, 0xf7, 0x0b, 0x14, 0x72, 0x7b,
	0x8e, 0xf5, 0x17, 0xbe, 0x84, 0x8a, 0xb0, 0x61, 0x2c, 0x6a, 0x40, 0x25, 0x1a, 0x1a, 0xe9, 0xa2,
	0xc0, 0x3a, 0x03, 0xb3, 0xb7, 0x90, 0x33, 0xf4, 0x24, 0x73, 0xa8, 0xc4, 0x97, 0x78, 0x88, 0x09,
	0xb5, 0x80, 0x0a, 0xf1, 0xe0, 0x73, 0x57, 0xfd, 0x41, 0x12, 0x5b, 0x07, 0xd0, 0x1c, 0xa2, 0x87,
	0x9c, 0x4a, 0x3c, 0x57, 0xb9, 0x4b, 0xff, 0x16, 0xbd, 0xe2, 0x2d, 0x0e, 0xe1, 0x67, 0x8e, 0x4b,
	0x5d, 0xb2, 0x01, 0x15, 0xb9, 0x4e, 0xc4, 0xb6, 0x30, 0xb0, 0xc6, 0xa0, 0x0f, 0x66, 0xd4, 0x9b,
	0x26, 0xa6, 0xd4, 0x94, 0x5d, 0x79, 0xe1, 0xde, 0xff, 0x80, 0x84, 0x07, 0xde, 0xf9, 0xff, 0x8c,
	0xb1, 0x23, 0x68, 0x0c, 0x38, 0x52, 0x89, 0xc9, 0x7b, 0xbf, 0xf2, 0x5a, 0x7b, 0x8f, 0xef, 0x40,
	0x53, 0x4d, 0x2e, 0x22, 0xa6, 0xc8, 0x31, 0x54, 0xa3, 0xe6, 0xe4, 0x47, 0xc4, 0x57, 0x37, 0x6b,
	0x96, 0xf9, 0x4d, 0x15, 0xb7, 0x90, 0xb3, 0xde, 0x90, 0x23, 0x78, 0xaf, 0xf0, 0x20, 0xba, 0x12,
	0x6d, 0xe2, 0x52, 0xe0, 0x3d, 0x01, 0x78, 0x06, 0x87, 0x18, 0x69, 0x7b, 0xfa, 0x2e, 0x05, 0x1d,
	0x6c, 0xf8, 0x9a, 0xc1, 0x13, 0xf9, 0x1d, 0x1b, 0x72, 0x59, 0x2b, 0xe8, 0xe9, 0x82, 0x9e, 0x49,
	0x07, 0x69, 0x27, 0x0b, 0xe6, 0x13, 0x67, 0xfe, 0x29, 0x16, 0x25, 0x53, 0x46, 0xa0, 0x6d, 0xc2,
	0x44, 0x9a, 0xf1, 0x03, 0x64, 0x31, 0x56, 0xb0, 0x6f, 0x1f, 0xea, 0x29, 0x96, 0xc8, 0x77, 0x25,
	0xdc, 0xe5, 0x2b, 0xbf, 0xc7, 0x75, 0x35, 0x2c, 0xec, 0x3f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa0,
	0xd0, 0x98, 0x30, 0x74, 0x04, 0x00, 0x00,
}
