// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts/account-service.proto

package accounts // import "github.com/metrix-io/proto/golang/accounts"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Account represents a user account.
//
// An account only contain the user's primary email address and
// phone number (if available). To view a secondary phone numbers
// or email addresses use one of the other RPC methods.
type Account struct {
	// The identifier of the user.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Subject is the fully qualified security identifier for this account.
	Sub string `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	// Username. The maximum length is 15 characters.
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// User's preferred e-mail address.
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// True if the user's e-mail address has been verified; otherwise false.
	EmailVerified bool     `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Profile       *Profile `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	// User's preferred phone number.
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// True if the user's phone number has been verified; otherwise false.
	PhoneNumberVerified bool `protobuf:"varint,8,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	// Unix timestamp when user account was created.
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp when user information was last updated.
	UpdatedAt int64 `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Unix timestamp when account was cancelled. Cancelled accounts are
	// automatically removed after one month.
	CancelledAt int64 `protobuf:"varint,11,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	// Unix timestamp when account was last logged in.
	LastLoginAt          int64    `protobuf:"varint,12,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *Account) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Account) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Account) GetPhoneNumberVerified() bool {
	if m != nil {
		return m.PhoneNumberVerified
	}
	return false
}

func (m *Account) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Account) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Account) GetCancelledAt() int64 {
	if m != nil {
		return m.CancelledAt
	}
	return 0
}

func (m *Account) GetLastLoginAt() int64 {
	if m != nil {
		return m.LastLoginAt
	}
	return 0
}

// *
// Profile is based loosely on the OpenID Connect userinfo specification:
// https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
//
// Be aware most fields are usually empty.
type Profile struct {
	// End-User's full name. The maximum length is 100 characters.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// First name(s) of the user. The maximum length is 30 characters.
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name(s) of the user. The maximum length is 30 characters.
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Middle name(s) of the user. The maximum length is 30 characters.
	MiddleName string `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	// Casual name of the user that may or may not be the same as the given_name.
	// The maximum length is 15 characters.
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// URL of user profile page. The maximum length is 255 characters.
	Profile string `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	// URL of user picture. The maximum length is 255 characters.
	Picture string `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	// URL of user web page or blog.
	Website string `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	// The gender is either "male", "female", "genderqueer" or empty.
	Gender string `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	// User's birthday is formatted in YYYY-MM-DD format.
	Birthdate string `protobuf:"bytes,10,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	// String from a time zone database representing the user's time zone.
	Zoneinfo string `protobuf:"bytes,11,opt,name=zoneinfo,proto3" json:"zoneinfo,omitempty"`
	// User's locale, represented as a BCP47 [RFC5646] language tag.
	Locale               string   `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{1}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Profile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Profile) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Profile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Profile) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *Profile) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Profile) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *Profile) GetZoneinfo() string {
	if m != nil {
		return m.Zoneinfo
	}
	return ""
}

func (m *Profile) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

// *
// Email contains an email address. Email addresses are always unique.
type Email struct {
	// Unique email identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The account to which this email belongs. An email can only belong
	// to 1 account.
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Email address.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// True if this email address has been verified; otherwise false.
	IsVerified bool `protobuf:"varint,4,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	// True if this is the user's preferred email address. Only 1 email address
	// can be primary.
	IsPrimary bool `protobuf:"varint,5,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	// Unix timestamp when email was created.
	CreatedAt int64 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp when email was last updated.
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{2}
}
func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (dst *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(dst, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Email) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Email) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *Email) GetIsPrimary() bool {
	if m != nil {
		return m.IsPrimary
	}
	return false
}

func (m *Email) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Email) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type GetAccountByIdRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountByIdRequest) Reset()         { *m = GetAccountByIdRequest{} }
func (m *GetAccountByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountByIdRequest) ProtoMessage()    {}
func (*GetAccountByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{3}
}
func (m *GetAccountByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountByIdRequest.Unmarshal(m, b)
}
func (m *GetAccountByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountByIdRequest.Merge(dst, src)
}
func (m *GetAccountByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountByIdRequest.Size(m)
}
func (m *GetAccountByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountByIdRequest proto.InternalMessageInfo

func (m *GetAccountByIdRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// *
// AddAccountRequest creates a new account.
//
// Returns a FailedPrecondition error if the email is already in use.
// Returns InvalidArgument errors if any of the fields are invalid.
type AddAccountRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Profile              *Profile `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountRequest) Reset()         { *m = AddAccountRequest{} }
func (m *AddAccountRequest) String() string { return proto.CompactTextString(m) }
func (*AddAccountRequest) ProtoMessage()    {}
func (*AddAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{4}
}
func (m *AddAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountRequest.Unmarshal(m, b)
}
func (m *AddAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountRequest.Marshal(b, m, deterministic)
}
func (dst *AddAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountRequest.Merge(dst, src)
}
func (m *AddAccountRequest) XXX_Size() int {
	return xxx_messageInfo_AddAccountRequest.Size(m)
}
func (m *AddAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountRequest proto.InternalMessageInfo

func (m *AddAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddAccountRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

// *
// UpdateAccountRequest allows to update user profile details.
type UpdateAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Profile              *Profile `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{5}
}
func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(dst, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateAccountRequest) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

// *
// UpdateAccount sends an empty response when the account has
// successfully been updated.
//
// Returns InvalidArgument errors if any of the fields are invalid.
type UpdateAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{6}
}
func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(dst, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

// *
// The login request marks a user as being logged in and returns
// the user account.
//
// It does not generate an authentication token; for this
// use the auth-service's login method.
type LoginRequest struct {
	// Login may contain either the email address or username
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{7}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// *
// ResendVerificationRequest schedules a reset password email.
//
// The link expires after 3 hours.
type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{8}
}
func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(dst, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// *
// ForgotPassword sends an empty response when a new forgot password
// email has been scheduled. Normally an email arrives within a couple of minutes.
//
// Returns a NotFound error code if the email address did not match any account.
type ForgotPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordResponse) Reset()         { *m = ForgotPasswordResponse{} }
func (m *ForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordResponse) ProtoMessage()    {}
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{9}
}
func (m *ForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordResponse.Unmarshal(m, b)
}
func (m *ForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordResponse.Merge(dst, src)
}
func (m *ForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordResponse.Size(m)
}
func (m *ForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordResponse proto.InternalMessageInfo

// *
// ResetPassword updates an account password using a reset token as proof.
type ResetPasswordRequest struct {
	ResetToken           string   `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{10}
}
func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(dst, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetResetToken() string {
	if m != nil {
		return m.ResetToken
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

// *
// ResetPassword sends an empty response when the password was updated
// successfully.
//
// Returns an NotFound error if the reset token does not exist or has
// expired.
type ResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{11}
}
func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(dst, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

// *
// UpdatePasswordRequest changes an account password with a user password as
// verification.
type UpdatePasswordRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{12}
}
func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(dst, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

// *
// UpdatePassword sends an empty response when the password was updated
// successfully.
//
// Returns an Unauthenticated error if the password was invalid.
// Returns a NotFound error if the account could not be found.
type UpdatePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{13}
}
func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(dst, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

// *
// VerifyEmailRequest verifies an email address.
//
// Returns an NotFound error if the token is invalid.
// Returns a FailedPrecondition if the email was already verified.
type VerifyEmailRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{14}
}
func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(dst, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// *
// VerifyEmail sends an empty response when the email was succesfully verified.
type VerifyEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailResponse) Reset()         { *m = VerifyEmailResponse{} }
func (m *VerifyEmailResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailResponse) ProtoMessage()    {}
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{15}
}
func (m *VerifyEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailResponse.Unmarshal(m, b)
}
func (m *VerifyEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailResponse.Marshal(b, m, deterministic)
}
func (dst *VerifyEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailResponse.Merge(dst, src)
}
func (m *VerifyEmailResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailResponse.Size(m)
}
func (m *VerifyEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailResponse proto.InternalMessageInfo

// *
// ResendVerificationRequest requests a new verification email.
// This is useful if the user forgot his or her email addresses.
type ResendVerificationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendVerificationRequest) Reset()         { *m = ResendVerificationRequest{} }
func (m *ResendVerificationRequest) String() string { return proto.CompactTextString(m) }
func (*ResendVerificationRequest) ProtoMessage()    {}
func (*ResendVerificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{16}
}
func (m *ResendVerificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendVerificationRequest.Unmarshal(m, b)
}
func (m *ResendVerificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendVerificationRequest.Marshal(b, m, deterministic)
}
func (dst *ResendVerificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendVerificationRequest.Merge(dst, src)
}
func (m *ResendVerificationRequest) XXX_Size() int {
	return xxx_messageInfo_ResendVerificationRequest.Size(m)
}
func (m *ResendVerificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendVerificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResendVerificationRequest proto.InternalMessageInfo

func (m *ResendVerificationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// *
// ResendVerification sends an empty response when a new verification
// email has been scheduled. Normally an email arrives within a couple
// of minutes.
//
// Returns a NotFound error code if the email address did not match
// any account.
//
// Returns a FailedPrecondition error code if the specified email
// address is already verified.
type ResendVerificationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendVerificationResponse) Reset()         { *m = ResendVerificationResponse{} }
func (m *ResendVerificationResponse) String() string { return proto.CompactTextString(m) }
func (*ResendVerificationResponse) ProtoMessage()    {}
func (*ResendVerificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{17}
}
func (m *ResendVerificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendVerificationResponse.Unmarshal(m, b)
}
func (m *ResendVerificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendVerificationResponse.Marshal(b, m, deterministic)
}
func (dst *ResendVerificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendVerificationResponse.Merge(dst, src)
}
func (m *ResendVerificationResponse) XXX_Size() int {
	return xxx_messageInfo_ResendVerificationResponse.Size(m)
}
func (m *ResendVerificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendVerificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResendVerificationResponse proto.InternalMessageInfo

// *
// CancelAccount disables an account and removes all auth tokens
// associated with the account.
//
// Cancelled accounts are completely removed after 14 days.
//
// To regain access to a cancelled account before the account is
// permanently deleted send an email to support@metrix.io
type CancelAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAccountRequest) Reset()         { *m = CancelAccountRequest{} }
func (m *CancelAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CancelAccountRequest) ProtoMessage()    {}
func (*CancelAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{18}
}
func (m *CancelAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAccountRequest.Unmarshal(m, b)
}
func (m *CancelAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CancelAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAccountRequest.Merge(dst, src)
}
func (m *CancelAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CancelAccountRequest.Size(m)
}
func (m *CancelAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAccountRequest proto.InternalMessageInfo

func (m *CancelAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// *
// CancelAccount sends an empty response when the account has
// successfully been cancelled.
type CancelAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAccountResponse) Reset()         { *m = CancelAccountResponse{} }
func (m *CancelAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CancelAccountResponse) ProtoMessage()    {}
func (*CancelAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_service_f0cef59229da8e47, []int{19}
}
func (m *CancelAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAccountResponse.Unmarshal(m, b)
}
func (m *CancelAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAccountResponse.Marshal(b, m, deterministic)
}
func (dst *CancelAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAccountResponse.Merge(dst, src)
}
func (m *CancelAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CancelAccountResponse.Size(m)
}
func (m *CancelAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Account)(nil), "metrixio.proto.accounts.v0.Account")
	proto.RegisterType((*Profile)(nil), "metrixio.proto.accounts.v0.Profile")
	proto.RegisterType((*Email)(nil), "metrixio.proto.accounts.v0.Email")
	proto.RegisterType((*GetAccountByIdRequest)(nil), "metrixio.proto.accounts.v0.GetAccountByIdRequest")
	proto.RegisterType((*AddAccountRequest)(nil), "metrixio.proto.accounts.v0.AddAccountRequest")
	proto.RegisterType((*UpdateAccountRequest)(nil), "metrixio.proto.accounts.v0.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "metrixio.proto.accounts.v0.UpdateAccountResponse")
	proto.RegisterType((*LoginRequest)(nil), "metrixio.proto.accounts.v0.LoginRequest")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "metrixio.proto.accounts.v0.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordResponse)(nil), "metrixio.proto.accounts.v0.ForgotPasswordResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "metrixio.proto.accounts.v0.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "metrixio.proto.accounts.v0.ResetPasswordResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "metrixio.proto.accounts.v0.UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "metrixio.proto.accounts.v0.UpdatePasswordResponse")
	proto.RegisterType((*VerifyEmailRequest)(nil), "metrixio.proto.accounts.v0.VerifyEmailRequest")
	proto.RegisterType((*VerifyEmailResponse)(nil), "metrixio.proto.accounts.v0.VerifyEmailResponse")
	proto.RegisterType((*ResendVerificationRequest)(nil), "metrixio.proto.accounts.v0.ResendVerificationRequest")
	proto.RegisterType((*ResendVerificationResponse)(nil), "metrixio.proto.accounts.v0.ResendVerificationResponse")
	proto.RegisterType((*CancelAccountRequest)(nil), "metrixio.proto.accounts.v0.CancelAccountRequest")
	proto.RegisterType((*CancelAccountResponse)(nil), "metrixio.proto.accounts.v0.CancelAccountResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*Account, error)
	GetAccountById(ctx context.Context, in *GetAccountByIdRequest, opts ...grpc.CallOption) (*Account, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Account, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error)
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
	ResendVerification(ctx context.Context, in *ResendVerificationRequest, opts ...grpc.CallOption) (*ResendVerificationResponse, error)
	CancelAccount(ctx context.Context, in *CancelAccountRequest, opts ...grpc.CallOption) (*CancelAccountResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/AddAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountById(ctx context.Context, in *GetAccountByIdRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/GetAccountById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error) {
	out := new(UpdatePasswordResponse)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/VerifyEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ResendVerification(ctx context.Context, in *ResendVerificationRequest, opts ...grpc.CallOption) (*ResendVerificationResponse, error) {
	out := new(ResendVerificationResponse)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/ResendVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CancelAccount(ctx context.Context, in *CancelAccountRequest, opts ...grpc.CallOption) (*CancelAccountResponse, error) {
	out := new(CancelAccountResponse)
	err := c.cc.Invoke(ctx, "/metrixio.proto.accounts.v0.AccountService/CancelAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	AddAccount(context.Context, *AddAccountRequest) (*Account, error)
	GetAccountById(context.Context, *GetAccountByIdRequest) (*Account, error)
	Login(context.Context, *LoginRequest) (*Account, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error)
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	ResendVerification(context.Context, *ResendVerificationRequest) (*ResendVerificationResponse, error)
	CancelAccount(context.Context, *CancelAccountRequest) (*CancelAccountResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_AddAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AddAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/AddAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AddAccount(ctx, req.(*AddAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/GetAccountById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountById(ctx, req.(*GetAccountByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/VerifyEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ResendVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ResendVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/ResendVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ResendVerification(ctx, req.(*ResendVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CancelAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CancelAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrixio.proto.accounts.v0.AccountService/CancelAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CancelAccount(ctx, req.(*CancelAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metrixio.proto.accounts.v0.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAccount",
			Handler:    _AccountService_AddAccount_Handler,
		},
		{
			MethodName: "GetAccountById",
			Handler:    _AccountService_GetAccountById_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AccountService_Login_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _AccountService_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AccountService_ResetPassword_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _AccountService_UpdatePassword_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _AccountService_VerifyEmail_Handler,
		},
		{
			MethodName: "ResendVerification",
			Handler:    _AccountService_ResendVerification_Handler,
		},
		{
			MethodName: "CancelAccount",
			Handler:    _AccountService_CancelAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/account-service.proto",
}

func init() {
	proto.RegisterFile("accounts/account-service.proto", fileDescriptor_account_service_f0cef59229da8e47)
}

var fileDescriptor_account_service_f0cef59229da8e47 = []byte{
	// 965 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x93, 0xa6, 0x89, 0x4f, 0xda, 0x08, 0x66, 0x9b, 0x62, 0xcc, 0x2e, 0x2d, 0x46, 0x48,
	0xd1, 0x8a, 0x26, 0xdb, 0xa2, 0xdd, 0x3b, 0x24, 0xb2, 0x08, 0xd0, 0x4a, 0x68, 0x55, 0x99, 0x1f,
	0xa1, 0xbd, 0x89, 0x1c, 0x7b, 0x9a, 0x0e, 0xeb, 0x78, 0x82, 0x67, 0xdc, 0x12, 0xee, 0x79, 0x09,
	0x6e, 0xe0, 0x79, 0xb8, 0xe0, 0x99, 0xd0, 0x9c, 0x19, 0x27, 0xb6, 0x93, 0xf5, 0x36, 0x7b, 0xe7,
	0xf3, 0x9d, 0xff, 0x9f, 0x6f, 0xa2, 0xc0, 0xc7, 0x41, 0x18, 0xf2, 0x2c, 0x91, 0x62, 0x64, 0x3e,
	0xce, 0x05, 0x4d, 0x6f, 0x59, 0x48, 0x87, 0x8b, 0x94, 0x4b, 0x4e, 0xdc, 0x39, 0x95, 0x29, 0xfb,
	0x9d, 0x71, 0x2d, 0x0f, 0x73, 0xf3, 0xe1, 0xed, 0x13, 0xef, 0xef, 0x26, 0xb4, 0xc7, 0x5a, 0x26,
	0x3d, 0x68, 0xb0, 0xc8, 0xb1, 0xce, 0xac, 0x81, 0xed, 0x37, 0x58, 0x44, 0xde, 0x83, 0xa6, 0xc8,
	0xa6, 0x4e, 0x03, 0x01, 0xf5, 0x49, 0x5c, 0xe8, 0x64, 0x82, 0xa6, 0x49, 0x30, 0xa7, 0x4e, 0x13,
	0xe1, 0x95, 0x4c, 0x8e, 0xa1, 0x45, 0xe7, 0x01, 0x8b, 0x9d, 0x7d, 0x54, 0x68, 0x81, 0x7c, 0x06,
	0x3d, 0xfc, 0x98, 0xdc, 0xd2, 0x94, 0x5d, 0x33, 0x1a, 0x39, 0xad, 0x33, 0x6b, 0xd0, 0xf1, 0x8f,
	0x10, 0xfd, 0xd9, 0x80, 0xe4, 0x4b, 0x68, 0x2f, 0x52, 0x7e, 0xcd, 0x62, 0xea, 0x1c, 0x9c, 0x59,
	0x83, 0xee, 0xe5, 0xa7, 0xc3, 0x37, 0x17, 0x3d, 0xbc, 0xd2, 0xa6, 0x7e, 0xee, 0x43, 0x3e, 0x81,
	0xc3, 0xc5, 0x0d, 0x4f, 0xe8, 0x24, 0xc9, 0xe6, 0x53, 0x9a, 0x3a, 0x6d, 0x2c, 0xa1, 0x8b, 0xd8,
	0x4b, 0x84, 0xc8, 0x25, 0xf4, 0x8b, 0x26, 0xeb, 0x7a, 0x3a, 0x58, 0xcf, 0x83, 0x82, 0xed, 0xaa,
	0xaa, 0x47, 0x00, 0x61, 0x4a, 0x03, 0x49, 0xa3, 0x49, 0x20, 0x1d, 0xfb, 0xcc, 0x1a, 0x34, 0x7d,
	0xdb, 0x20, 0x63, 0xa9, 0xd4, 0xd9, 0x22, 0xca, 0xd5, 0xa0, 0xd5, 0x06, 0x19, 0x4b, 0x55, 0x54,
	0x18, 0x24, 0x21, 0x8d, 0x63, 0x6d, 0xd0, 0x45, 0x83, 0xee, 0x0a, 0x1b, 0x4b, 0xe2, 0xc1, 0x51,
	0x1c, 0x08, 0x39, 0x89, 0xf9, 0x8c, 0x25, 0xca, 0xe6, 0x50, 0xdb, 0x28, 0xf0, 0x7b, 0x85, 0x8d,
	0xa5, 0xf7, 0x5f, 0x03, 0xda, 0xa6, 0x61, 0x42, 0x60, 0x1f, 0x67, 0xaf, 0x77, 0x84, 0xdf, 0xaa,
	0x8a, 0x6b, 0x96, 0x0a, 0x39, 0x41, 0x8d, 0x5e, 0x96, 0x8d, 0xc8, 0x4b, 0xa5, 0xfe, 0x08, 0x6c,
	0x4c, 0x51, 0xdc, 0x99, 0x02, 0x50, 0x79, 0x0a, 0xdd, 0x39, 0x8b, 0xa2, 0x98, 0x6a, 0xb5, 0xde,
	0x1c, 0x68, 0x08, 0x0d, 0x5c, 0xe8, 0x24, 0x2c, 0x7c, 0x8d, 0xda, 0x96, 0x76, 0xce, 0x65, 0xe2,
	0x94, 0x77, 0x66, 0xaf, 0xd7, 0xa1, 0x34, 0x2c, 0x94, 0x59, 0x4a, 0xcd, 0x26, 0x72, 0x51, 0x69,
	0xee, 0xe8, 0x54, 0x30, 0x49, 0x71, 0xee, 0xb6, 0x9f, 0x8b, 0xe4, 0x04, 0x0e, 0x66, 0x34, 0x89,
	0x68, 0x8a, 0x73, 0xb6, 0x7d, 0x23, 0x91, 0x87, 0x60, 0x4f, 0x59, 0x2a, 0x6f, 0xd4, 0x54, 0x71,
	0xc6, 0xb6, 0xbf, 0x06, 0x54, 0x7d, 0x7f, 0xf0, 0x84, 0xb2, 0xe4, 0x9a, 0xe3, 0x7c, 0x6d, 0x7f,
	0x25, 0xab, 0x88, 0x31, 0x0f, 0x83, 0x98, 0xe2, 0x54, 0x6d, 0xdf, 0x48, 0xde, 0xbf, 0x16, 0xb4,
	0xbe, 0xc1, 0xe3, 0xac, 0x1e, 0xfc, 0x23, 0x00, 0x73, 0x66, 0x13, 0x16, 0xe5, 0xa3, 0x34, 0xc8,
	0x8b, 0x68, 0x7d, 0xe1, 0xcd, 0xe2, 0x85, 0x9f, 0x42, 0x97, 0x89, 0xf5, 0x39, 0xed, 0xe3, 0x39,
	0x01, 0x13, 0xc5, 0x2b, 0x62, 0x62, 0xb2, 0x48, 0xd9, 0x3c, 0x48, 0x97, 0xe6, 0xfc, 0x6d, 0x26,
	0xae, 0x34, 0x50, 0x39, 0xb2, 0x83, 0xfa, 0x23, 0x6b, 0x57, 0x8e, 0xcc, 0x7b, 0x06, 0xfd, 0xef,
	0xa8, 0x34, 0x0c, 0x7e, 0xbe, 0x7c, 0x11, 0xf9, 0xf4, 0xb7, 0x8c, 0x0a, 0x59, 0xe9, 0xc5, 0xaa,
	0xf4, 0xe2, 0xfd, 0x63, 0xc1, 0xfb, 0xe3, 0x28, 0x32, 0x8e, 0xb9, 0xd3, 0xaa, 0x43, 0xab, 0xd8,
	0x61, 0x91, 0xf5, 0x8d, 0x0a, 0xeb, 0x5d, 0xe8, 0x2c, 0x02, 0x21, 0xee, 0x78, 0x1a, 0xe5, 0xd7,
	0x95, 0xcb, 0x45, 0x52, 0xef, 0xef, 0x4e, 0x6a, 0x4f, 0xc2, 0xf1, 0x4f, 0xd8, 0x67, 0xa5, 0xc8,
	0xfa, 0xce, 0x8a, 0x59, 0x9b, 0xef, 0x90, 0xf5, 0x03, 0xe8, 0x57, 0xb2, 0x8a, 0x05, 0x4f, 0x04,
	0xf5, 0xbe, 0x82, 0x43, 0xa4, 0x64, 0x61, 0x56, 0x48, 0xdb, 0x7c, 0x56, 0x28, 0x94, 0xe6, 0xd1,
	0x28, 0xcf, 0xc3, 0x3b, 0x87, 0xfe, 0xb7, 0x3c, 0x9d, 0x71, 0x79, 0x65, 0x90, 0xda, 0xb1, 0x7b,
	0x0e, 0x9c, 0x54, 0xcd, 0x4d, 0x29, 0xaf, 0xe0, 0xd8, 0xa7, 0x82, 0x6e, 0xc4, 0x39, 0x85, 0x6e,
	0xaa, 0xf0, 0x89, 0xe4, 0xaf, 0x69, 0x5e, 0x18, 0x20, 0xf4, 0xa3, 0x42, 0xd4, 0x93, 0x94, 0xd0,
	0xbb, 0x49, 0xa5, 0xc2, 0x6e, 0x42, 0xef, 0xf2, 0x50, 0xaa, 0xff, 0x4a, 0x6c, 0x93, 0x34, 0xcb,
	0x07, 0x53, 0xcd, 0xfa, 0x96, 0x7d, 0xd4, 0x4c, 0x64, 0xa3, 0x9e, 0xe6, 0x66, 0x3d, 0x0e, 0x9c,
	0x54, 0xd3, 0x9a, 0x82, 0x1e, 0x03, 0x41, 0x8e, 0x2d, 0x91, 0xcc, 0x85, 0x59, 0x16, 0xbb, 0xd7,
	0x82, 0xd7, 0x87, 0x07, 0x25, 0x5b, 0x13, 0xe2, 0x02, 0x3e, 0x54, 0xcd, 0x26, 0x91, 0x26, 0x6b,
	0x18, 0x48, 0xc6, 0x93, 0xfa, 0xad, 0x3c, 0x04, 0x77, 0x9b, 0x8b, 0x09, 0xf8, 0x14, 0x8e, 0xbf,
	0xc6, 0xf7, 0x7d, 0xa7, 0x9b, 0x55, 0x43, 0xaf, 0xb8, 0xe9, 0x78, 0x97, 0x7f, 0x75, 0xa0, 0x67,
	0xb0, 0x1f, 0xf4, 0x6f, 0x3a, 0x99, 0x02, 0xac, 0x89, 0x4b, 0xce, 0xeb, 0x8e, 0x7b, 0x83, 0xe0,
	0x6e, 0x2d, 0x17, 0x8c, 0xad, 0xb7, 0x47, 0x7e, 0x85, 0x5e, 0xf9, 0x55, 0x21, 0x17, 0x75, 0x8e,
	0x5b, 0x5f, 0xa0, 0xfb, 0xe6, 0xfa, 0x05, 0x5a, 0xc8, 0x2b, 0x32, 0xa8, 0xb3, 0x2f, 0x52, 0xef,
	0xbe, 0x91, 0x97, 0xd0, 0x2b, 0x13, 0xa8, 0xbe, 0x8b, 0xad, 0xdc, 0x74, 0x2f, 0x77, 0x71, 0x31,
	0x57, 0xb0, 0x47, 0x6e, 0xe1, 0xa8, 0xc4, 0x22, 0xf2, 0xa4, 0x2e, 0xcc, 0x36, 0x32, 0xbb, 0x17,
	0x3b, 0x78, 0xac, 0xf2, 0x2e, 0xa1, 0x57, 0x66, 0x4b, 0x7d, 0xcb, 0x5b, 0x09, 0x5d, 0xdf, 0xf2,
	0x1b, 0xc8, 0xb8, 0x47, 0x16, 0xd0, 0x2d, 0x50, 0x8c, 0x0c, 0xeb, 0x82, 0x6c, 0xf2, 0xd6, 0x1d,
	0xdd, 0xdb, 0x7e, 0x95, 0xf1, 0x4f, 0x0b, 0xc8, 0x26, 0x17, 0xc9, 0xd3, 0xb7, 0x0d, 0x6e, 0x2b,
	0xdd, 0xdd, 0x67, 0xbb, 0xba, 0x15, 0x97, 0x5d, 0x62, 0x6f, 0xfd, 0xb2, 0xb7, 0xbd, 0x0f, 0xf5,
	0xcb, 0xde, 0xfa, 0x34, 0x78, 0x7b, 0xcf, 0x3f, 0x7f, 0xf5, 0x78, 0xc6, 0xe4, 0x4d, 0x36, 0x1d,
	0x86, 0x7c, 0x3e, 0xd2, 0x01, 0xce, 0x19, 0x1f, 0x61, 0x84, 0xd1, 0x8c, 0xc7, 0x41, 0x32, 0xcb,
	0xff, 0x12, 0x88, 0xe9, 0x01, 0xc2, 0x5f, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x83, 0xae,
	0x9a, 0x2e, 0x0c, 0x00, 0x00,
}
